/* ===================================================
   KumbhSathi — App Data
   All static data: events, listings, news, akharas,
   map markers, transport info, etc.
   Edit this file to update content.
   =================================================== */

/* ===== FIRST SHAHI SNAN DATE (countdown target) ===== */
const FIRST_SHAHI_SNAN_DATE = new Date('2027-08-29T05:30:00+05:30');

/* ===== SHAHI SNAN DATES ===== */
const SHAHI_SNAN_DATES = [
  {
    id: 'ss1',
    date: '2027-08-29',
    day: 29, month: 'Aug', year: 2027,
    tithi: 'श्रावण पूर्णिमा (Shravan Purnima)',
    title_en: 'First Shahi Snan — Niranjani Akhara & Anand Akhara',
    title_hi: 'प्रथम शाही स्नान — निरंजनी अखाड़ा',
    title_mr: 'पहिले शाही स्नान — निरंजनी आखाडा',
    location: 'Ramkund Ghat & Trimbakeshwar',
    time: '04:00 AM – 12:00 PM',
    significance_en: 'The first royal bath marks the beginning of the Simhastha Kumbh Mela. Niranjani and Anand Akharas take the holy dip first at Ramkund.',
    type: 'shahi',
  },
  {
    id: 'ss2',
    date: '2027-09-12',
    day: 12, month: 'Sep', year: 2027,
    tithi: 'भाद्रपद अमावस्या (Bhadrapad Amavasya)',
    title_en: 'Second Shahi Snan — Juna Akhara',
    title_hi: 'द्वितीय शाही स्नान — जूना अखाड़ा',
    title_mr: 'दुसरे शाही स्नान — जुना आखाडा',
    location: 'Ramkund Ghat, Nashik',
    time: '03:30 AM – 12:00 PM',
    significance_en: 'Juna Akhara, the largest akhara, performs the Shahi Snan on Bhadrapad Amavasya. Lakhs of devotees gather at Ramkund.',
    type: 'shahi',
  },
  {
    id: 'ss3',
    date: '2027-09-27',
    day: 27, month: 'Sep', year: 2027,
    tithi: 'महालया अमावस्या (Mahalaya Amavasya)',
    title_en: 'Third Shahi Snan — Mahanirvani & Atal Akhara',
    title_hi: 'तृतीय शाही स्नान — महानिर्वाणी अखाड़ा',
    title_mr: 'तिसरे शाही स्नान — महानिर्वाणी आखाडा',
    location: 'Ramkund, Nashik & Kushavart Kund, Trimbakeshwar',
    time: '04:00 AM – 01:00 PM',
    significance_en: 'The third and final major Shahi Snan during Simhastha. All akharas participate in this grand event at Ramkund.',
    type: 'shahi',
  },
];

/* ===== EVENTS (Schedule page) ===== */
const EVENTS_DATA = [
  ...SHAHI_SNAN_DATES,
  {
    id: 'ev1',
    date: '2027-08-01',
    day: 1, month: 'Aug', year: 2027,
    tithi: 'सिंहस्थ कुंभ उद्घाटन',
    title_en: 'Official Inauguration of Simhastha Kumbh Mela',
    title_hi: 'सिंहस्थ कुंभ मेले का आधिकारिक उद्घाटन',
    title_mr: 'सिंहस्थ कुंभ मेळ्याचे अधिकृत उद्घाटन',
    location: 'Ramkund Ground, Nashik',
    time: '10:00 AM',
    significance_en: 'Grand inauguration ceremony with Puja, procession of Akharas and cultural programs. VIP dignitaries and saints to be present.',
    type: 'religious',
  },
  {
    id: 'ev2',
    date: '2027-08-05',
    day: 5, month: 'Aug', year: 2027,
    tithi: 'श्रावण पंचमी',
    title_en: 'Naga Sadhu Procession — Peshwai',
    title_hi: 'नागा साधु जुलूस — पेशवाई',
    title_mr: 'नागा साधू मिरवणूक — पेशवाई',
    location: 'Main Road Nashik → Ramkund',
    time: '08:00 AM – 02:00 PM',
    significance_en: 'Spectacular procession of Naga Sadhus, elephants, horses, and decorated chariots through the streets of Nashik.',
    type: 'cultural',
  },
  {
    id: 'ev3',
    date: '2027-08-15',
    day: 15, month: 'Aug', year: 2027,
    tithi: 'स्वतंत्रता दिवस',
    title_en: 'Independence Day Special Puja & Cultural Night',
    title_hi: 'स्वतंत्रता दिवस विशेष पूजा और सांस्कृतिक संध्या',
    title_mr: 'स्वातंत्र्य दिन विशेष पूजा व सांस्कृतिक संध्या',
    location: 'Ramkund Amphitheater',
    time: '06:00 PM – 10:00 PM',
    significance_en: 'Special Independence Day celebration at the Kumbh grounds with classical music, folk dances, and patriotic performances.',
    type: 'cultural',
  },
  {
    id: 'ev4',
    date: '2027-08-20',
    day: 20, month: 'Aug', year: 2027,
    tithi: 'श्रावण शिवरात्रि',
    title_en: 'Shravan Shivratri — Rudrabhishek',
    title_hi: 'श्रावण शिवरात्रि — रुद्राभिषेक',
    title_mr: 'श्रावण शिवरात्री — रुद्राभिषेक',
    location: 'Trimbakeshwar Mandir, Trimbakeshwar',
    time: '12:00 AM – 06:00 AM',
    significance_en: 'Grand Rudrabhishek at Trimbakeshwar Temple with 108 priests. One of the most auspicious nights of the Kumbh.',
    type: 'religious',
  },
  {
    id: 'ev5',
    date: '2027-09-01',
    day: 1, month: 'Sep', year: 2027,
    tithi: 'भाद्रपद प्रथमा',
    title_en: 'Ganesh Utsav Celebrations at Kumbh',
    title_hi: 'गणेश उत्सव समारोह',
    title_mr: 'गणेशोत्सव सोहळा',
    location: 'Kumbh Cultural Stage, Nashik',
    time: '04:00 PM – 11:00 PM',
    significance_en: 'Kumbh Mela special Ganesh Utsav with classical and folk performances, bringing Maharashtra\'s greatest festival to the holy grounds.',
    type: 'cultural',
  },
  {
    id: 'ev6',
    date: '2027-09-10',
    day: 10, month: 'Sep', year: 2027,
    tithi: 'पितृ पक्ष आरंभ',
    title_en: 'Pitru Paksha Begins — Tarpan at Ramkund',
    title_hi: 'पितृ पक्ष आरंभ — रामकुंड पर तर्पण',
    title_mr: 'पितृपक्ष प्रारंभ — रामकुंड तर्पण',
    location: 'Ramkund, Nashik',
    time: '06:00 AM – 12:00 PM',
    significance_en: 'Sacred Tarpan rituals for ancestors at Ramkund. Nashik is one of the most holy places for Pitru Paksha ceremonies.',
    type: 'religious',
  },
  {
    id: 'ev7',
    date: '2027-10-05',
    day: 5, month: 'Oct', year: 2027,
    tithi: 'विजयादशमी (दशहरा)',
    title_en: 'Vijaya Dashami — Kumbh Closing Ceremony',
    title_hi: 'विजयादशमी — कुंभ समापन समारोह',
    title_mr: 'विजयादशमी — कुंभ समारोप सोहळा',
    location: 'Ramkund Ground, Nashik',
    time: '10:00 AM – 06:00 PM',
    significance_en: 'Grand closing ceremony of Simhastha Kumbh Mela on Vijayadashami with final Shahi processions and ceremonial farewell.',
    type: 'religious',
  },
];

/* Localized event detail text used when a live schedule sheet has no translation columns. */
const EVENT_TRANSLATIONS = {
  ss1: {
    en: { tithi: 'Shravan Purnima' },
    hi: { tithi: 'श्रावण पूर्णिमा', significance: 'पहला शाही स्नान सिंहस्थ कुंभ मेले का शुभारंभ करता है। निरंजनी और आनंद अखाड़े सबसे पहले Ramkund में पवित्र स्नान करते हैं।' },
    mr: { tithi: 'श्रावण पौर्णिमा', significance: 'पहिले Shahi Snan सिंहस्थ कुंभमेळ्याची सुरुवात करते. निरंजनी आणि आनंद आखाडे Ramkund येथे सर्वप्रथम पवित्र स्नान करतात.' },
  },
  ss2: {
    en: { tithi: 'Bhadrapad Amavasya' },
    hi: { tithi: 'भाद्रपद अमावस्या', significance: 'भाद्रपद अमावस्या पर सबसे बड़ा अखाड़ा, जूना अखाड़ा, Shahi Snan करता है। Ramkund में लाखों श्रद्धालु एकत्र होते हैं।' },
    mr: { tithi: 'भाद्रपद अमावस्या', significance: 'भाद्रपद अमावस्येला सर्वात मोठा जूना आखाडा Shahi Snan करतो. Ramkund येथे लाखो भाविक एकत्र येतात.' },
  },
  ss3: {
    en: { tithi: 'Mahalaya Amavasya' },
    hi: { tithi: 'महालया अमावस्या', significance: 'सिंहस्थ के दौरान यह तीसरा और अंतिम प्रमुख Shahi Snan है। Ramkund में सभी अखाड़े इस भव्य आयोजन में शामिल होते हैं।' },
    mr: { tithi: 'महालया अमावस्या', significance: 'सिंहस्थमधील हे तिसरे आणि अंतिम प्रमुख Shahi Snan आहे. Ramkund येथील या भव्य सोहळ्यात सर्व आखाडे सहभागी होतात.' },
  },
  ev1: {
    en: { tithi: 'Simhastha Kumbh Opening' },
    hi: { tithi: 'सिंहस्थ कुंभ उद्घाटन', significance: 'पूजा, अखाड़ों की शोभायात्रा और सांस्कृतिक कार्यक्रमों के साथ भव्य उद्घाटन समारोह होगा। विशिष्ट अतिथि और संत उपस्थित रहेंगे।' },
    mr: { tithi: 'सिंहस्थ कुंभ उद्घाटन', significance: 'पूजा, आखाड्यांची मिरवणूक आणि सांस्कृतिक कार्यक्रमांसह भव्य उद्घाटन सोहळा होईल. मान्यवर आणि संत उपस्थित राहतील.' },
  },
  ev2: {
    en: { tithi: 'Shravan Panchami' },
    hi: { tithi: 'श्रावण पंचमी', significance: 'नाशिक की सड़कों से नागा साधुओं, हाथियों, घोड़ों और सजे हुए रथों की भव्य शोभायात्रा निकलेगी।' },
    mr: { tithi: 'श्रावण पंचमी', significance: 'नाशिकच्या रस्त्यांवरून नागा साधू, हत्ती, घोडे आणि सजवलेल्या रथांची भव्य मिरवणूक निघेल.' },
  },
  ev3: {
    en: { tithi: 'Independence Day' },
    hi: { tithi: 'स्वतंत्रता दिवस', significance: 'कुंभ क्षेत्र में शास्त्रीय संगीत, लोकनृत्य और देशभक्ति प्रस्तुतियों के साथ स्वतंत्रता दिवस मनाया जाएगा।' },
    mr: { tithi: 'स्वातंत्र्यदिन', significance: 'कुंभ परिसरात शास्त्रीय संगीत, लोकनृत्य आणि देशभक्तिपर सादरीकरणांसह स्वातंत्र्यदिन साजरा केला जाईल.' },
  },
  ev4: {
    en: { tithi: 'Shravan Shivratri' },
    hi: { tithi: 'श्रावण शिवरात्रि', significance: 'त्र्यंबकेश्वर मंदिर में 108 पुजारियों द्वारा भव्य रुद्राभिषेक होगा। यह कुंभ की सबसे शुभ रात्रियों में से एक है।' },
    mr: { tithi: 'श्रावण शिवरात्री', significance: 'त्र्यंबकेश्वर मंदिरात 108 पुजाऱ्यांच्या हस्ते भव्य रुद्राभिषेक होईल. ही कुंभातील सर्वात शुभ रात्रींपैकी एक आहे.' },
  },
  ev5: {
    en: { tithi: 'Bhadrapad Prathama' },
    hi: { tithi: 'भाद्रपद प्रथमा', significance: 'कुंभ मेले में गणेशोत्सव के शास्त्रीय और लोक प्रस्तुतियों वाले कार्यक्रम होंगे, जिनसे महाराष्ट्र का प्रमुख त्योहार पवित्र क्षेत्र तक पहुँचेगा।' },
    mr: { tithi: 'भाद्रपद प्रतिपदा', significance: 'कुंभमेळ्यात शास्त्रीय आणि लोककलांच्या सादरीकरणांसह गणेशोत्सव साजरा होईल; महाराष्ट्राचा हा प्रमुख उत्सव पवित्र परिसरात रंगेल.' },
  },
  ev6: {
    en: { tithi: 'Pitru Paksha Begins' },
    hi: { tithi: 'पितृ पक्ष आरंभ', significance: 'Ramkund में पूर्वजों के लिए पवित्र तर्पण अनुष्ठान होंगे। पितृ पक्ष के कर्मकांडों के लिए नाशिक को विशेष पवित्र माना जाता है।' },
    mr: { tithi: 'पितृपक्षारंभ', significance: 'Ramkund येथे पूर्वजांसाठी पवित्र तर्पण विधी होतील. पितृपक्षातील विधींसाठी नाशिक अत्यंत पवित्र मानले जाते.' },
  },
  ev7: {
    en: { tithi: 'Vijaya Dashami (Dussehra)' },
    hi: { tithi: 'विजयादशमी (दशहरा)', significance: 'विजयादशमी पर सिंहस्थ कुंभ मेले का भव्य समापन होगा। अंतिम शाही शोभायात्राओं के बाद औपचारिक विदाई दी जाएगी।' },
    mr: { tithi: 'विजयादशमी (दसरा)', significance: 'विजयादशमीला सिंहस्थ कुंभमेळ्याचा भव्य समारोप होईल. अंतिम शाही मिरवणुकांनंतर औपचारिक निरोप दिला जाईल.' },
  },
};

/* STAY_DATA removed — Stay page now loads live from Google Sheet */
const _STAY_DATA_REMOVED = true; // placeholder so references fail loudly

if (false) { const __unused = [
  {
    id: 'st1',
    name: 'Hotel Sai Heritage',
    type: 'Hotel',
    category: 'premium',
    price: '₹3,500 – ₹7,000',
    distance: '0.5 km from Ramkund',
    contact: '+91 98765 43210',
    rating: 4.5,
    sponsored: true,
    description: 'Luxury hotel with AC rooms, restaurant, rooftop view of Godavari river. Special Kumbh packages available.',
    facilities: ['AC', 'Restaurant', 'WiFi', 'Parking'],
    image: 'https://picsum.photos/seed/hotel1/300/180',
  },
  {
    id: 'st2',
    name: 'Kumbh Grand Resort',
    type: 'Resort',
    category: 'premium',
    price: '₹4,000 – ₹9,000',
    distance: '1.2 km from Ramkund',
    contact: '+91 98765 43211',
    rating: 4.8,
    sponsored: true,
    description: 'Premium resort with all modern amenities, swimming pool, and dedicated Kumbh concierge service.',
    facilities: ['AC', 'Pool', 'Restaurant', 'Spa', 'WiFi'],
    image: 'https://picsum.photos/seed/hotel2/300/180',
  },
  {
    id: 'st3',
    name: 'Trimbakeshwar Ashram Stay',
    type: 'Ashram',
    category: 'dharam',
    price: 'Free / Donation',
    distance: '0.2 km from Trimbakeshwar Temple',
    contact: '+91 97654 32109',
    rating: 4.2,
    sponsored: false,
    description: 'Traditional ashram accommodation with vegetarian meals, yoga, and spiritual programs. Donation-based.',
    facilities: ['Meals Included', 'Yoga', 'Meditation'],
    image: 'https://picsum.photos/seed/ashram1/300/180',
  },
  {
    id: 'st4',
    name: 'Nashik Dharamshala',
    type: 'Dharamshala',
    category: 'dharam',
    price: '₹200 – ₹400',
    distance: '0.8 km from Ramkund',
    contact: '+91 96543 21098',
    rating: 3.8,
    sponsored: false,
    description: 'Affordable dharamshala with basic facilities. Suitable for families and pilgrims. Clean and safe.',
    facilities: ['Common Bathrooms', 'Safe Lockers'],
    image: 'https://picsum.photos/seed/dharam1/300/180',
  },
  {
    id: 'st5',
    name: 'Hotel Panchavati Inn',
    type: 'Hotel',
    category: 'mid',
    price: '₹1,200 – ₹2,500',
    distance: '0.3 km from Ramkund',
    contact: '+91 95432 10987',
    rating: 4.0,
    sponsored: true,
    description: 'Mid-range hotel centrally located near Panchavati and Ramkund. Great value for Kumbh pilgrims.',
    facilities: ['AC Available', 'Restaurant', 'Parking'],
    image: 'https://picsum.photos/seed/hotel3/300/180',
  },
  {
    id: 'st6',
    name: 'Godavari Guest House',
    type: 'Guest House',
    category: 'budget',
    price: '₹600 – ₹1,000',
    distance: '0.4 km from Ramkund',
    contact: '+91 94321 09876',
    rating: 3.5,
    sponsored: false,
    description: 'Budget-friendly guest house with clean rooms, attached bathroom. River view from some rooms.',
    facilities: ['Hot Water', 'Fan Rooms', 'Parking'],
    image: 'https://picsum.photos/seed/guesthouse1/300/180',
  },
  {
    id: 'st7',
    name: 'Kumbh Tent City (Government)',
    type: 'Tent Camp',
    category: 'budget',
    price: '₹500 – ₹1,500',
    distance: '1.0 km from Ramkund',
    contact: '+91 93210 98765',
    rating: 3.9,
    sponsored: false,
    description: 'Official government-run tent city with basic amenities. Shared bathrooms and common dining.',
    facilities: ['Shared Bathrooms', 'Meals', 'Security'],
    image: 'https://picsum.photos/seed/tent1/300/180',
  },
  {
    id: 'st8',
    name: 'Om Shanti Dharamshala',
    type: 'Dharamshala',
    category: 'dharam',
    price: 'Free (Registration Required)',
    distance: '0.6 km from Ramkund',
    contact: '+91 92109 87654',
    rating: 4.1,
    sponsored: false,
    description: 'Free accommodation for genuine pilgrims. Vegetarian sattvic food available. Prior registration needed.',
    facilities: ['Free Meals', 'Puja Hall', 'Safe Lockers'],
    image: 'https://picsum.photos/seed/dharam2/300/180',
  },
  {
    id: 'st9',
    name: 'Hotel Trimbak Palace',
    type: 'Hotel',
    category: 'mid',
    price: '₹1,800 – ₹3,000',
    distance: '0.3 km from Trimbakeshwar Temple',
    contact: '+91 91098 76543',
    rating: 4.3,
    sponsored: false,
    description: 'Well-appointed hotel near Trimbakeshwar Temple with modern amenities and excellent service.',
    facilities: ['AC', 'Restaurant', 'WiFi', 'Parking'],
    image: 'https://picsum.photos/seed/hotel4/300/180',
  },
  {
    id: 'st10',
    name: 'Sadguru Ashram & Guest House',
    type: 'Ashram',
    category: 'budget',
    price: '₹300 – ₹600',
    distance: '1.5 km from Ramkund',
    contact: '+91 90987 65432',
    rating: 4.0,
    sponsored: false,
    description: 'Spiritual ashram with simple accommodation, daily satsang, and nutritious vegetarian meals.',
    facilities: ['Meals', 'Satsang Hall', 'Yoga'],
    image: 'https://picsum.photos/seed/ashram2/300/180',
  },
  {
    id: 'st11',
    name: 'Hotel Panorama Nashik',
    type: 'Hotel',
    category: 'premium',
    price: '₹5,000 – ₹12,000',
    distance: '2.0 km from Ramkund',
    contact: '+91 89876 54321',
    rating: 4.7,
    sponsored: false,
    description: 'Luxury 4-star hotel with panoramic views, rooftop restaurant, and exclusive Kumbh packages for VIP guests.',
    facilities: ['AC', 'Pool', 'Restaurant', 'Gym', 'Spa', 'WiFi'],
    image: 'https://picsum.photos/seed/hotel5/300/180',
  },
]; } // end if(false) — STAY_DATA removed

/* ===== NEWS DATA ===== */
const NEWS_DATA = [
  {
    id: 'n1',
    category: 'announce',
    headline_en: 'Nashik Kumbh 2027: Government Announces ₹5,000 Crore Infrastructure Plan',
    headline_hi: 'नाशिक कुंभ 2027: सरकार ने ₹5,000 करोड़ के बुनियादी ढांचे की घोषणा की',
    headline_mr: 'नाशिक कुंभ 2027: सरकारने ₹5,000 कोटी पायाभूत सुविधांची घोषणा केली',
    date: '15 Jan 2027',
    short_en: 'Maharashtra government approves a massive ₹5,000 crore infrastructure plan for Nashik and Trimbakeshwar to handle the unprecedented crowd during Simhastha Kumbh 2027.',
    short_hi: 'महाराष्ट्र सरकार ने सिंहस्थ कुंभ 2027 में आने वाली बड़ी भीड़ के लिए नाशिक और त्र्यंबकेश्वर में ₹5,000 करोड़ की बुनियादी ढाँचा योजना मंज़ूर की है।',
    short_mr: 'सिंहस्थ कुंभ 2027 मधील मोठ्या गर्दीच्या व्यवस्थेसाठी महाराष्ट्र सरकारने नाशिक आणि त्र्यंबकेश्वरमध्ये ₹5,000 कोटींची पायाभूत सुविधा योजना मंजूर केली आहे.',
    full_en: 'Maharashtra government has approved a massive ₹5,000 crore infrastructure development plan for Nashik and Trimbakeshwar ahead of Simhastha Kumbh Mela 2027. The plan includes construction of 8 new ghats, widening of 45 roads, installation of 10,000 CCTV cameras, 50 new parking zones, and a state-of-the-art crowd monitoring system. Chief Minister confirmed that over 5 crore pilgrims are expected during the 3-month event.',
    image: 'https://picsum.photos/seed/news1/200/130',
  },
  {
    id: 'n2',
    category: 'vip',
    headline_en: 'Prime Minister to Attend Inauguration of Nashik Kumbh 2027',
    headline_hi: 'प्रधानमंत्री नाशिक कुंभ 2027 के उद्घाटन में शामिल होंगे',
    headline_mr: 'पंतप्रधान नाशिक कुंभ 2027 च्या उद्घाटनाला उपस्थित राहणार',
    date: '28 Feb 2027',
    short_en: 'Prime Minister confirmed to inaugurate the Simhastha Kumbh Mela 2027 at Nashik on August 1st, 2027 along with religious leaders and Chief Minister.',
    short_hi: 'प्रधानमंत्री 1 अगस्त 2027 को नाशिक में सिंहस्थ कुंभ मेले का उद्घाटन करेंगे। इस अवसर पर धार्मिक नेता और मुख्यमंत्री भी उपस्थित रहेंगे।',
    short_mr: '1 ऑगस्ट 2027 रोजी नाशिक येथे सिंहस्थ कुंभमेळ्याचे उद्घाटन पंतप्रधान करणार असून धार्मिक नेते आणि मुख्यमंत्री उपस्थित राहतील.',
    full_en: 'The Prime Minister of India has confirmed attendance at the official inauguration of Simhastha Kumbh Mela 2027 at Nashik on August 1st. The event will be attended by the Chief Minister of Maharashtra, Union Ministers, and prominent saints and religious leaders from across India. A grand cultural program featuring artists from all 28 states has been planned. Security arrangements for the VIP visit are being coordinated by NSG and state police.',
    image: 'https://picsum.photos/seed/news2/200/130',
  },
  {
    id: 'n3',
    category: 'weather',
    headline_en: 'IMD Forecast: Normal Monsoon Expected During Nashik Kumbh Period',
    headline_hi: 'IMD पूर्वानुमान: नाशिक कुंभ के दौरान सामान्य मानसून की उम्मीद',
    headline_mr: 'IMD अंदाज: नाशिक कुंभ काळात सामान्य पाऊस अपेक्षित',
    date: '10 Mar 2027',
    short_en: 'India Meteorological Department forecasts normal monsoon rainfall during the Nashik Kumbh period. Pilgrims advised to carry light rain gear.',
    short_hi: 'मौसम विभाग ने कुंभ अवधि में सामान्य मानसून वर्षा का अनुमान दिया है। यात्रियों को हल्का वर्षा-सामान साथ रखने की सलाह है।',
    short_mr: 'कुंभ काळात नेहमीसारखा पाऊस अपेक्षित असल्याचा हवामान विभागाचा अंदाज आहे. भाविकांनी हलकी पावसाळी साधने सोबत ठेवावीत.',
    full_en: 'India Meteorological Department (IMD) has released its forecast indicating normal monsoon rainfall patterns for the Nashik region during the August-September 2027 Kumbh period. Average rainfall of 80-100mm per month is expected. While rainfall during Shahi Snan days may occur, authorities are well-prepared. Pilgrims are advised to carry lightweight rain gear and check weather updates regularly. Emergency shelters are being set up at all major ghat points.',
    image: 'https://picsum.photos/seed/news3/200/130',
  },
  {
    id: 'n4',
    category: 'announce',
    headline_en: 'Free Shuttle Service Between Nashik and Trimbakeshwar During Kumbh',
    headline_hi: 'कुंभ के दौरान नाशिक और त्र्यंबकेश्वर के बीच मुफ्त शटल सेवा',
    headline_mr: 'कुंभ काळात नाशिक व त्र्यंबकेश्वर दरम्यान मोफत शटल सेवा',
    date: '5 Apr 2027',
    short_en: 'Maharashtra MSRTC announces free shuttle bus service connecting Nashik and Trimbakeshwar every 15 minutes throughout the Kumbh Mela period.',
    short_hi: 'महाराष्ट्र MSRTC ने कुंभ मेले के दौरान नाशिक और त्र्यंबकेश्वर के बीच हर 15 मिनट में मुफ्त शटल बस चलाने की घोषणा की है।',
    short_mr: 'कुंभमेळ्याच्या काळात नाशिक आणि त्र्यंबकेश्वरदरम्यान दर 15 मिनिटांनी मोफत शटल बस चालवण्याची घोषणा महाराष्ट्र MSRTC ने केली आहे.',
    full_en: 'Maharashtra State Road Transport Corporation (MSRTC) has announced a free shuttle bus service connecting Nashik city and Trimbakeshwar throughout the Simhastha Kumbh Mela 2027. Buses will operate every 15 minutes from 4 AM to midnight. Special buses for elderly and differently-abled pilgrims will be available. Over 500 buses have been dedicated for this service. The shuttle will operate from Nashik Bus Stand, Panchavati, Ramkund, and all major akhara camps.',
    image: 'https://picsum.photos/seed/news4/200/130',
  },
  {
    id: 'n5',
    category: 'traffic',
    headline_en: 'Traffic Diversion Plan Released for Nashik City During Shahi Snan Days',
    headline_hi: 'शाही स्नान के दिनों के लिए नाशिक में यातायात डायवर्जन योजना जारी',
    headline_mr: 'शाही स्नानाच्या दिवसांसाठी नाशिकमध्ये वाहतूक बदल योजना जाहीर',
    date: '20 May 2027',
    short_en: 'Nashik Police releases detailed traffic diversion plan for Shahi Snan days. Private vehicles to be restricted within 5km of Ramkund.',
    short_hi: 'नाशिक पुलिस ने Shahi Snan के दिनों के लिए यातायात योजना जारी की है। Ramkund के 5 किमी के दायरे में निजी वाहनों पर रोक रहेगी।',
    short_mr: 'नाशिक पोलिसांनी Shahi Snan दिवसांसाठी वाहतूक योजना जाहीर केली आहे. Ramkund पासून 5 किमी परिसरात खासगी वाहनांना प्रवेश नसेल.',
    full_en: 'Nashik Police has released a detailed traffic management and diversion plan for the three Shahi Snan days during Simhastha Kumbh 2027. Private vehicles will be restricted within a 5km radius of Ramkund Ghat on Shahi Snan days. 45 parking zones have been designated at various points across Nashik. Park-and-walk, park-and-shuttle facilities are available. Out-of-state vehicles arriving via Highway NH3 and NH60 will be directed to designated parking areas.',
    image: 'https://picsum.photos/seed/news5/200/130',
  },
  {
    id: 'n6',
    category: 'announce',
    headline_en: '50,000 Security Personnel to Be Deployed for Nashik Kumbh 2027',
    headline_hi: 'नाशिक कुंभ 2027 के लिए 50,000 सुरक्षाकर्मी तैनात होंगे',
    headline_mr: 'नाशिक कुंभ 2027 साठी 50,000 सुरक्षा जवान तैनात होणार',
    date: '1 Jun 2027',
    short_en: 'Maharashtra Home Department approves deployment of 50,000 police and security personnel including CRPF companies for Kumbh security.',
    short_hi: 'महाराष्ट्र गृह विभाग ने कुंभ की सुरक्षा के लिए CRPF सहित 50,000 पुलिस और सुरक्षा कर्मियों की तैनाती मंज़ूर की है।',
    short_mr: 'कुंभच्या सुरक्षेसाठी CRPF सह 50,000 पोलीस आणि सुरक्षा कर्मचाऱ्यांच्या तैनातीला महाराष्ट्र गृह विभागाने मंजुरी दिली आहे.',
    full_en: 'The Maharashtra Home Department has approved deployment of 50,000 police and security personnel for Simhastha Kumbh Mela 2027. This includes state police, CRPF companies, NSG for VIP protection, fire brigade teams, and 5,000 home guards. AI-powered crowd monitoring systems will be installed at 50 strategic points. Lost and found centers will operate at 10 locations. A dedicated control room will coordinate all emergency responses.',
    image: 'https://picsum.photos/seed/news6/200/130',
  },
  {
    id: 'n7',
    category: 'vip',
    headline_en: 'Spiritual Leaders from 12 Countries to Attend Nashik Kumbh 2027',
    headline_hi: '12 देशों के आध्यात्मिक नेता नाशिक कुंभ 2027 में शामिल होंगे',
    headline_mr: '12 देशांतील अध्यात्मिक नेते नाशिक कुंभ 2027 ला उपस्थित राहणार',
    date: '15 Jun 2027',
    short_en: 'Spiritual leaders, sadhus, and delegations from 12 countries including USA, UK, Germany, Japan, and Australia to attend Nashik Kumbh.',
    short_hi: 'USA, UK, Germany, Japan और Australia सहित 12 देशों के आध्यात्मिक नेता, साधु और प्रतिनिधिमंडल नाशिक कुंभ में शामिल होंगे।',
    short_mr: 'USA, UK, Germany, Japan आणि Australia यांसह 12 देशांतील आध्यात्मिक नेते, साधू आणि प्रतिनिधी नाशिक कुंभात सहभागी होतील.',
    full_en: 'The Ministry of External Affairs has confirmed participation of spiritual leaders and cultural delegations from 12 countries at Simhastha Kumbh Mela Nashik 2027. Delegations from USA, UK, Germany, France, Japan, Australia, Singapore, South Africa, Brazil, Canada, Nepal, and Sri Lanka will be present. Special arrangements for international pilgrims including translation services, international food options, and dedicated accommodation zones are being prepared.',
    image: 'https://picsum.photos/seed/news7/200/130',
  },
  {
    id: 'n8',
    category: 'announce',
    headline_en: 'KumbhSathi App Launched: Digital Guide for Nashik Kumbh Pilgrims',
    headline_hi: 'कुंभसाथी ऐप लॉन्च: नाशिक कुंभ यात्रियों के लिए डिजिटल गाइड',
    headline_mr: 'कुंभसाथी ऐप लॉन्च: नाशिक कुंभ भाविकांसाठी डिजिटल मार्गदर्शक',
    date: '1 Jul 2027',
    short_en: 'Official KumbhSathi mobile app launched to help pilgrims navigate Nashik Kumbh 2027 with maps, schedules, emergency contacts, and lost & found services.',
    short_hi: 'यात्रियों की मदद के लिए KumbhSathi ऐप शुरू हुआ है। इसमें नक्शे, कार्यक्रम, आपातकालीन संपर्क और खोया-पाया सुविधा उपलब्ध हैं।',
    short_mr: 'भाविकांसाठी नकाशे, वेळापत्रक, आपत्कालीन संपर्क आणि हरवले-सापडले सेवा देणारे KumbhSathi अॅप सुरू झाले आहे.',
    full_en: 'The KumbhSathi mobile application has been officially launched as the comprehensive digital companion for pilgrims attending Simhastha Kumbh Mela Nashik 2027. The app features interactive maps with OpenStreetMap, complete event schedules, accommodation listings, transport guides, emergency helplines, and a lost & found reporting system. Available in English, Hindi, and Marathi. The app works offline and is available as a Progressive Web App installable on any smartphone.',
    image: 'https://picsum.photos/seed/news8/200/130',
  },
];

/* ===== AKHARAS DATA ===== */
const AKHARAS_DATA = [
  {
    id: 'ak1',
    name: 'श्री पंचायती अखाड़ा महानिर्वाणी',
    name_en: 'Mahanirvani Akhara',
    name_mr: 'श्री पंचायती महानिर्वाणी आखाडा',
    type: 'शैव (Shaiva)',
    camp: 'Panchavati Camp Ground, Nashik',
    deity: 'Lord Shiva (Kapila)',
    est: 'Est. 8th century CE',
    desc_hi: 'यह सबसे प्राचीन और सम्मानित अखाड़ों में से एक है। इसकी स्थापना आदि गुरु शंकराचार्य ने की थी। महानिर्वाणी अखाड़ा शाही स्नान में प्रथम स्थान प्राप्त करने वाला अखाड़ा है।',
    desc_mr: 'हा सर्वात प्राचीन आणि मान्यवर शैव आखाड्यांपैकी एक आहे. आदि गुरु शंकराचार्यांनी त्याची स्थापना केली. Shahi Snan मिरवणुकीत महानिर्वाणी आखाड्याला प्रथम स्थान आहे.',
    desc_en: 'One of the oldest and most revered Shaiva akharas, founded by Adi Guru Shankaracharya. Mahanirvani Akhara holds the first position in the Shahi Snan procession.',
    icon: '🕉️',
  },
  {
    id: 'ak2',
    name: 'श्री पंचदशनाम जूना अखाड़ा',
    name_en: 'Juna Akhara',
    name_mr: 'श्री पंचदशनाम जुना आखाडा',
    type: 'शैव — नागा (Shaiva Naga)',
    camp: 'Godavari Camp Area, Nashik',
    deity: 'Lord Dattatreya',
    est: 'Est. 13th century CE',
    desc_hi: 'जूना अखाड़ा सबसे बड़ा और सबसे प्रसिद्ध अखाड़ा है। इसमें 5 लाख से अधिक साधु सदस्य हैं। नागा साधुओं की अनूठी परंपराओं के लिए जाना जाता है।',
    desc_mr: 'जुना आखाडा हा सर्वात मोठा आणि प्रसिद्ध आखाडा असून त्यात 5 लाखांहून अधिक साधू सदस्य आहेत. नागा साधूंच्या अनोख्या परंपरांसाठी तो ओळखला जातो.',
    desc_en: 'Juna Akhara is the largest akhara with over 5 lakh member sadhus. Famous for its Naga Sadhus and unique spiritual traditions. Also known as Bhairav Akhara.',
    icon: '🔱',
  },
  {
    id: 'ak3',
    name: 'श्री पंचायती अखाड़ा निरंजनी',
    name_en: 'Niranjani Akhara',
    name_mr: 'श्री पंचायती निरंजनी आखाडा',
    type: 'शैव (Shaiva)',
    camp: 'Ramkund Camp, Nashik',
    deity: 'Lord Kartik',
    est: 'Est. 904 CE',
    desc_hi: 'निरंजनी अखाड़ा शाही स्नान में दूसरे स्थान पर है। इसकी स्थापना 904 CE में हुई। यह अखाड़ा सात प्रमुख शैव अखाड़ों में से एक है।',
    desc_mr: 'Shahi Snan मिरवणुकीत निरंजनी आखाड्याला दुसरे स्थान आहे. त्याची स्थापना इ.स. 904 मध्ये झाली. हा सात प्रमुख शैव आखाड्यांपैकी एक आहे.',
    desc_en: 'Niranjani Akhara holds the second position in Shahi Snan. Founded in 904 CE, it is one of the seven major Shaiva akharas and is known for its scholarly traditions.',
    icon: '☀️',
  },
  {
    id: 'ak4',
    name: 'श्री पंचायती अटल अखाड़ा',
    name_en: 'Atal Akhara',
    name_mr: 'श्री पंचायती अटल आखाडा',
    type: 'शैव (Shaiva)',
    camp: 'Trimbakeshwar Camp',
    deity: 'Lord Ganesha',
    est: 'Est. 569 CE',
    desc_hi: 'अटल अखाड़ा सबसे छोटे पंच अखाड़ों में से एक है। लेकिन इसकी परंपराएं बेहद प्राचीन हैं। भगवान गणेश इस अखाड़े के इष्ट देव हैं।',
    desc_mr: 'अटल आखाडा पंच आखाड्यांपैकी आकाराने लहान असला, तरी त्याची परंपरा प्राचीन आहे. भगवान गणेश हे या आखाड्याचे आराध्य दैवत आहेत.',
    desc_en: 'Atal Akhara, though one of the smaller akharas, has ancient traditions dating back to 569 CE. Lord Ganesha is the presiding deity. Known for its Vedic scholarship.',
    icon: '🐘',
  },
  {
    id: 'ak5',
    name: 'श्री निर्मल पंचायती अखाड़ा',
    name_en: 'Nirmal Akhara',
    name_mr: 'श्री निर्मल पंचायती आखाडा',
    type: 'सिख (Sikh)',
    camp: 'Nashik Camp Zone B',
    deity: 'Guru Granth Sahib',
    est: 'Est. 1784 CE',
    desc_hi: 'निर्मल अखाड़ा सिख परंपरा का प्रतिनिधित्व करता है। इसकी स्थापना 1784 CE में दसवें गुरु की आज्ञा से हुई। यह कुंभ में सिख-हिंदू एकता का प्रतीक है।',
    desc_mr: 'निर्मल आखाडा कुंभात शीख परंपरेचे प्रतिनिधित्व करतो. दहाव्या गुरूंच्या आज्ञेने त्याची स्थापना इ.स. 1784 मध्ये झाली. तो शीख-हिंदू एकतेचे प्रतीक आहे.',
    desc_en: 'Nirmal Akhara represents the Sikh tradition at Kumbh, founded in 1784 CE. It is a symbol of Sikh-Hindu unity and participates in all Kumbh rituals alongside Shaiva and Vaishnava akharas.',
    icon: '✡️',
  },
  {
    id: 'ak6',
    name: 'श्री वैष्णव दिगंबर अखाड़ा',
    name_en: 'Digambar Akhara (Vaishnava)',
    name_mr: 'श्री वैष्णव दिगंबर आखाडा',
    type: 'वैष्णव (Vaishnava)',
    camp: 'Godavari Bank Camp, Nashik',
    deity: 'Lord Vishnu',
    est: 'Est. Ancient',
    desc_hi: 'दिगंबर अखाड़ा वैष्णव संप्रदाय का प्रमुख अखाड़ा है। भगवान विष्णु के भक्त साधुओं का यह संगम भारत की अद्वितीय धार्मिक परंपराओं को जीवंत रखता है।',
    desc_mr: 'दिगंबर आखाडा हा वैष्णव संप्रदायातील प्रमुख आखाडा असून भगवान विष्णूचे भक्त साधू येथे सहभागी होतात. तो भारताच्या अद्वितीय धार्मिक परंपरा जिवंत ठेवतो.',
    desc_en: 'Digambar Akhara is a prominent Vaishnava akhara devoted to Lord Vishnu. Represents the Vaishnava sampradaya tradition and participates in Vaishnava Shahi Snan at Ramkund.',
    icon: '🌺',
  },
  {
    id: 'ak7',
    name: 'श्री पंचायती उदासीन अखाड़ा (बड़ा)',
    name_en: 'Bada Udaseen Akhara',
    name_mr: 'श्री पंचायती उदासीन आखाडा (मोठा)',
    type: 'उदासीन (Udaseen)',
    camp: 'Nashik Camp Zone C',
    deity: 'Lord Ram & Shiva',
    est: 'Est. 17th century',
    desc_hi: 'उदासीन संप्रदाय की स्थापना श्री चंद्र जी महाराज ने की थी। यह अखाड़ा गुरु नानक के पुत्र श्री चंद्र की परंपरा को आगे बढ़ाता है।',
    desc_mr: 'उदासीन संप्रदायाची स्थापना श्री चंद्रजी महाराजांनी केली. हा आखाडा गुरू नानकांचे पुत्र श्री चंद्र यांची परंपरा पुढे चालवतो.',
    desc_en: 'Founded in the Udaseen tradition by Sri Chandra Ji Maharaj, son of Guru Nanak. This akhara bridges Sikh and Hindu traditions and participates actively in Kumbh Mela.',
    icon: '🕊️',
  },
];

/* ===== TRANSPORT DATA ===== */
const TRANSPORT_DATA = {
  byTrain: [
    {
      route: 'Mumbai → Nashik Road Station',
      duration: '~3 hours',
      cost: '₹150 – ₹600 (Class dependent)',
      trains: ['Panchavati Express', 'Tapovan Express', 'Mumbai-Manmad Passenger'],
      info: 'Nashik Road is the main railway station, 8km from city centre. Frequent trains from CSMT, Dadar, Kalyan.',
      info_hi: 'नाशिक रोड मुख्य रेलवे स्टेशन है और शहर के केंद्र से 8 किमी दूर है। CSMT, दादर और कल्याण से नियमित ट्रेनें उपलब्ध हैं।',
      info_mr: 'नाशिक रोड हे शहराच्या केंद्रापासून 8 किमी अंतरावरील मुख्य रेल्वे स्थानक आहे. CSMT, दादर आणि कल्याणहून नियमित गाड्या उपलब्ध आहेत.',
    },
    {
      route: 'Pune → Nashik Road',
      duration: '~4 hours',
      cost: '₹200 – ₹700',
      trains: ['Nashik Express', 'Intercity Express'],
      info: 'Change at Manmad or direct trains available. Check IRCTC for special Kumbh trains.',
      info_hi: 'मनमाड में ट्रेन बदलें या सीधी ट्रेन लें। विशेष कुंभ ट्रेनों के लिए IRCTC देखें।',
      info_mr: 'मनमाड येथे गाडी बदला किंवा थेट गाडीने जा. विशेष कुंभ गाड्यांसाठी IRCTC तपासा.',
    },
    {
      route: 'Aurangabad → Nashik Road',
      duration: '~3.5 hours',
      cost: '₹150 – ₹550',
      trains: ['Intercity services', 'Passenger trains'],
      info: 'Via Manmad Junction. Several daily connections available.',
      info_hi: 'मनमाड जंक्शन के रास्ते जाएँ। रोज़ कई ट्रेनें उपलब्ध हैं।',
      info_mr: 'मनमाड जंक्शनमार्गे जा. दररोज अनेक गाड्या उपलब्ध आहेत.',
    },
  ],
  byBus: [
    {
      route: 'Mumbai → Nashik',
      duration: '~4-5 hours',
      cost: '₹200 – ₹500 (AC/Non-AC)',
      operator: 'MSRTC, Private Volvo buses',
      info: 'Buses depart from Dadar, Borivali, Thane, and CSMT. Every 30 minutes during Kumbh peak.',
      info_hi: 'बसें दादर, बोरीवली, ठाणे और CSMT से चलती हैं। कुंभ के व्यस्त समय में हर 30 मिनट पर बस मिलेगी।',
      info_mr: 'दादर, बोरिवली, ठाणे आणि CSMT येथून बसेस सुटतात. कुंभच्या गर्दीच्या काळात दर 30 मिनिटांनी बस उपलब्ध असेल.',
    },
    {
      route: 'Pune → Nashik',
      duration: '~4-5 hours',
      cost: '₹250 – ₹600',
      operator: 'MSRTC, Private operators',
      info: 'Multiple buses daily. Book in advance during Kumbh peak season.',
      info_hi: 'रोज़ कई बसें उपलब्ध हैं। कुंभ के व्यस्त मौसम में पहले से बुक करें।',
      info_mr: 'दररोज अनेक बसेस उपलब्ध आहेत. कुंभच्या गर्दीच्या हंगामात आगाऊ आरक्षण करा.',
    },
    {
      route: 'Aurangabad → Nashik',
      duration: '~3 hours',
      cost: '₹180 – ₹400',
      operator: 'MSRTC',
      info: 'Frequent service. Via Yeola junction.',
      info_hi: 'नियमित बस सेवा उपलब्ध है। मार्ग येवला जंक्शन से होकर जाता है।',
      info_mr: 'नियमित बस सेवा उपलब्ध आहे. मार्ग येवला जंक्शनमार्गे जातो.',
    },
  ],
  byAir: [
    {
      airport: 'Nashik Airport (Ozar)',
      dist: '20 km from Nashik city',
      flights: 'Mumbai, Hyderabad, Bengaluru',
      info: 'Ozar Airport has limited commercial flights. During Kumbh, special flights may be added. Check airlines for latest schedules.',
      info_hi: 'ओझर हवाई अड्डे से सीमित नियमित उड़ानें हैं। कुंभ के दौरान विशेष उड़ानें शुरू हो सकती हैं; ताज़ा समय-सारणी के लिए एयरलाइन से जाँचें।',
      info_mr: 'ओझर विमानतळावरून मर्यादित व्यावसायिक उड्डाणे आहेत. कुंभकाळात विशेष उड्डाणे सुरू होऊ शकतात; अद्ययावत वेळापत्रकासाठी विमान कंपनीकडे तपासा.',
    },
    {
      airport: 'Pune Airport (PNQ)',
      dist: '210 km from Nashik',
      info: 'Nearest major airport. Well-connected internationally. Take bus/taxi from Pune to Nashik (4-5 hrs).',
      info_hi: 'यह सबसे नज़दीकी बड़ा हवाई अड्डा है और अंतरराष्ट्रीय उड़ानों से जुड़ा है। पुणे से नाशिक बस या टैक्सी से जाएँ (4–5 घंटे)।',
      info_mr: 'हे सर्वात जवळचे मोठे विमानतळ असून आंतरराष्ट्रीय उड्डाणांनी जोडलेले आहे. पुण्याहून नाशिकला बस किंवा टॅक्सीने जा (4–5 तास).',
    },
    {
      airport: 'Chhatrapati Shivaji Maharaj (BOM)',
      dist: '170 km from Nashik',
      info: 'Mumbai Airport — best connected internationally. Multiple transport options to Nashik: bus, train, cab.',
      info_hi: 'मुंबई हवाई अड्डा अंतरराष्ट्रीय उड़ानों से सबसे अच्छी तरह जुड़ा है। नाशिक के लिए बस, ट्रेन और टैक्सी उपलब्ध हैं।',
      info_mr: 'मुंबई विमानतळ आंतरराष्ट्रीय उड्डाणांनी उत्तमरीत्या जोडलेले आहे. नाशिकसाठी बस, रेल्वे आणि टॅक्सीचे पर्याय उपलब्ध आहेत.',
    },
  ],
  byRoad: [
    {
      route: 'Mumbai → Nashik',
      highway: 'NH-160 (Kasara Ghat) or NH-61 (Bhiwandi-Igatpuri)',
      duration: '~3.5 – 4.5 hours',
      dist: '~170 km',
      info: 'NH-160 is the main route via Kasara. NH-61 via Bhiwandi-Igatpuri is more scenic but slower.',
      info_hi: 'कसारा घाट से होकर NH-160 मुख्य मार्ग है। भिवंडी–इगतपुरी से NH-61 अधिक सुंदर है, लेकिन धीमा है।',
      info_mr: 'कसारा घाटमार्गे NH-160 हा मुख्य मार्ग आहे. भिवंडी–इगतपुरीमार्गे NH-61 अधिक निसर्गरम्य आहे, पण धीमा आहे.',
    },
    {
      route: 'Pune → Nashik',
      highway: 'NH-60 (via Shirdi) or via Sangamner',
      duration: '~4 – 5 hours',
      dist: '~210 km',
      info: 'NH-60 via Shirdi is the fastest route. Via Sangamner adds extra 30 min but avoids highway tolls.',
      info_hi: 'शिर्डी से होकर NH-60 सबसे तेज़ मार्ग है। संगमनेर का रास्ता लगभग 30 मिनट लंबा है, लेकिन राजमार्ग टोल से बचाता है।',
      info_mr: 'शिर्डीमार्गे NH-60 हा सर्वात जलद मार्ग आहे. संगमनेरमार्गे प्रवास सुमारे 30 मिनिटे जास्त, पण महामार्ग टोल टाळता येतो.',
    },
    {
      route: 'Aurangabad → Nashik',
      highway: 'NH-752C via Yeola',
      duration: '~3 hours',
      dist: '~105 km',
      info: 'Good quality road. Route passes through Yeola, famous for its handwoven Paithani sarees.',
      info_hi: 'सड़क अच्छी स्थिति में है। मार्ग येवला से होकर जाता है, जो हाथ से बुनी पैठणी साड़ियों के लिए प्रसिद्ध है।',
      info_mr: 'रस्ता चांगल्या स्थितीत आहे. हा मार्ग हातमागावरील पैठणी साड्यांसाठी प्रसिद्ध असलेल्या येवल्यातून जातो.',
    },
  ],
  local: [
    {
      mode: 'Free Shuttle Bus',
      icon: 'fa-bus',
      route: 'Nashik Bus Stand ↔ Ramkund ↔ Trimbakeshwar',
      frequency: 'Every 15 minutes (4 AM – 12 AM)',
      cost: 'FREE during Kumbh',
    },
    {
      mode: 'Auto Rickshaw',
      icon: 'fa-taxi',
      route: 'Anywhere in Nashik city',
      frequency: 'On demand (pre-paid counter at station)',
      cost: '₹30 minimum, ₹15/km after 1.5km',
    },
    {
      mode: 'City Bus (MSRTC)',
      icon: 'fa-bus',
      route: 'Routes 1–32 covering all major areas',
      frequency: 'Every 10-15 min on main routes',
      cost: '₹10 – ₹25 flat fare during Kumbh',
    },
    {
      mode: 'Nashik → Trimbakeshwar',
      icon: 'fa-van-shuttle',
      route: 'Direct: 28 km distance',
      frequency: 'Shuttle every 15 min / Cab on demand',
      cost: 'Free shuttle / ₹400-600 cab (shared: ₹80-100)',
    },
  ],
};

/* ===== HOSPITALS DATA ===== */
const HOSPITALS_DATA = [
  { name: 'Civil Hospital Nashik', addr: 'Near CBS, Nashik', phone: '0253-2577000', emergency: true },
  { name: 'Wockhardt Hospital', addr: 'Gangapur Rd, Nashik', phone: '0253-6604444', emergency: true },
  { name: 'Trimbak General Hospital', addr: 'Main Rd, Trimbakeshwar', phone: '02594-233244', emergency: true },
  { name: 'Nashik Civil Trauma Centre', addr: 'Nashik Road', phone: '0253-2464000', emergency: true },
  { name: 'Nashik District Disaster Management', addr: 'Nashik District', phone: '1077', emergency: true },
];

/* ===== FIRST AID TIPS ===== */
const FIRST_AID_DATA = [
  {
    title_en: 'Heat Stroke & Dehydration',
    title_hi: 'लू और निर्जलीकरण',
    title_mr: 'उष्माघात आणि निर्जलीकरण',
    tips_en: [
      'Move the person to shade immediately',
      'Give ORS / cold water to drink slowly',
      'Apply wet cloth on head and neck',
      'Fan the person to cool down body',
      'Seek medical help if unconscious',
    ],
    tips_hi: [
      'व्यक्ति को तुरंत छाया में ले जाएँ',
      'ORS या ठंडा पानी धीरे-धीरे पिलाएँ',
      'सिर और गर्दन पर गीला कपड़ा रखें',
      'शरीर को ठंडा करने के लिए हवा करें',
      'बेहोशी की स्थिति में तुरंत चिकित्सा सहायता लें',
    ],
    tips_mr: [
      'व्यक्तीला त्वरित सावलीत न्या',
      'ORS किंवा थंड पाणी हळूहळू पिण्यास द्या',
      'डोके आणि मानेवर ओले कापड ठेवा',
      'शरीर थंड करण्यासाठी हवा घाला',
      'बेशुद्ध असल्यास त्वरित वैद्यकीय मदत घ्या',
    ],
  },
  {
    title_en: 'Crowd Crush / Stampede',
    title_hi: 'भीड़ में दबना',
    title_mr: 'गर्दीत चेंगराचेंगरी',
    tips_en: [
      'Don\'t panic — move with the crowd flow',
      'Keep arms bent at elbow to protect chest',
      'If down, curl into a ball and protect head',
      'Call out loudly for help',
      'Move to sides, not against the crowd',
    ],
    tips_hi: [
      'घबराएँ नहीं — भीड़ के बहाव के साथ चलें',
      'छाती की रक्षा के लिए कोहनियाँ मोड़कर रखें',
      'गिर जाएँ तो सिकुड़कर सिर की रक्षा करें',
      'मदद के लिए ज़ोर से आवाज़ दें',
      'भीड़ के विरुद्ध नहीं, किनारों की ओर जाएँ',
    ],
    tips_mr: [
      'घाबरू नका — गर्दीच्या प्रवाहासोबत चला',
      'छातीचे संरक्षण करण्यासाठी कोपरे वाकवून ठेवा',
      'पडल्यास शरीर आकसून डोक्याचे संरक्षण करा',
      'मदतीसाठी मोठ्याने हाका मारा',
      'गर्दीच्या विरुद्ध न जाता बाजूला सरका',
    ],
  },
  {
    title_en: 'Getting Lost at Kumbh',
    title_hi: 'भीड़ में खो जाने पर',
    title_mr: 'कुंभमेळ्यात हरवल्यास',
    tips_en: [
      'Call emergency services on 112',
      'Go to nearest Police Booth',
      'Stay at a landmark — don\'t wander',
      'Use the KumbhSathi Lost & Found feature',
      'Share your location with family',
    ],
    tips_hi: [
      '112 पर आपातकालीन सहायता के लिए कॉल करें',
      'नज़दीकी पुलिस बूथ पर जाएँ',
      'किसी पहचान योग्य स्थान पर रुकें — भटकें नहीं',
      'KumbhSathi के खोया-पाया फ़ीचर का उपयोग करें',
      'परिवार के साथ अपनी लोकेशन साझा करें',
    ],
    tips_mr: [
      'आपत्कालीन मदतीसाठी 112 वर कॉल करा',
      'जवळच्या पोलीस चौकीत जा',
      'ओळखण्याजोग्या ठिकाणी थांबा — भटकू नका',
      'KumbhSathi मधील हरवले-सापडले सुविधा वापरा',
      'कुटुंबासोबत तुमचे स्थान शेअर करा',
    ],
  },
  {
    title_en: 'Snake Bite',
    title_hi: 'सर्पदंश',
    title_mr: 'सर्पदंश',
    tips_en: [
      'Keep the bitten area still and below heart level',
      'Do NOT suck, cut, or apply tourniquet',
      'Remove jewelry/tight clothing near bite',
      'Note time of bite and snake appearance',
      'Rush to nearest hospital immediately — call 108',
    ],
    tips_hi: [
      'काटे हुए हिस्से को स्थिर और हृदय से नीचे रखें',
      'ज़हर चूसें नहीं, काटें नहीं और कसकर न बाँधें',
      'काटे के पास के गहने या तंग कपड़े हटा दें',
      'काटने का समय और साँप का रूप याद रखें',
      'तुरंत नज़दीकी अस्पताल जाएँ — 108 पर कॉल करें',
    ],
    tips_mr: [
      'दंश झालेला भाग स्थिर आणि हृदयापेक्षा खाली ठेवा',
      'विष चोखू नका, जखम कापू नका किंवा घट्ट बांधू नका',
      'दंशाजवळील दागिने किंवा घट्ट कपडे काढा',
      'दंशाची वेळ आणि सापाचे स्वरूप लक्षात ठेवा',
      'त्वरित जवळच्या रुग्णालयात जा — 108 वर कॉल करा',
    ],
  },
  {
    title_en: 'Drowning / Water Accident',
    title_hi: 'डूबने की स्थिति में',
    title_mr: 'बुडणे / पाण्यातील अपघात',
    tips_en: [
      'Call 112 or 108 immediately',
      'Don\'t jump into water if untrained',
      'Throw a rope or floating object',
      'Once out, lay person on side to drain water',
      'Begin CPR if not breathing — call 108',
    ],
    tips_hi: [
      'तुरंत 112 या 108 पर कॉल करें',
      'प्रशिक्षित न हों तो पानी में न कूदें',
      'रस्सी या तैरने वाली वस्तु फेंकें',
      'बाहर निकालने के बाद व्यक्ति को करवट पर लिटाएँ',
      'साँस न चल रही हो तो CPR शुरू करें — 108 पर कॉल करें',
    ],
    tips_mr: [
      'त्वरित 112 किंवा 108 वर कॉल करा',
      'प्रशिक्षित नसल्यास पाण्यात उडी मारू नका',
      'दोरी किंवा तरंगणारी वस्तू फेका',
      'पाण्याबाहेर काढल्यावर व्यक्तीला कुशीवर झोपवा',
      'श्वास सुरू नसल्यास CPR सुरू करा — 108 वर कॉल करा',
    ],
  },
];

/* ===== MAP MARKERS ===== */
const MAP_MARKERS = {
  ghats: [
    { name: 'Ramkund Ghat, Panchavati, Nashik', lat: 20.007544, lng: 73.792541, info: 'Main bathing ghat for Kumbh Mela' },
    { name: 'Kushavarta Kund, Trimbakeshwar', lat: 19.932886, lng: 73.529883, info: 'Sacred ghat at Trimbakeshwar' },
    { name: 'Gandhi Talav, Nashik', lat: 20.006940, lng: 73.792400, info: 'Ghat near Ramkund' },
    { name: 'Laxman Kund, Nashik', lat: 20.007600, lng: 73.792300, info: 'Sacred ghat near Ramkund' },
    { name: 'Sita Sarovar, Nashik', lat: 20.008400, lng: 73.796100, info: 'Sacred water site near Panchavati' },
    { name: 'Ahilyadevi Ghat, Nashik', lat: 20.007200, lng: 73.792600, info: 'Ghat on the Godavari river' },
  ],
  temples: [
    { name: 'Kalaram Temple, Panchavati, Nashik', lat: 20.006981, lng: 73.795092, info: 'Historic temple in Panchavati' },
    { name: 'Trimbakeshwar Jyotirlinga Temple', lat: 19.935789, lng: 73.527086, info: 'One of 12 Jyotirlingas' },
    { name: 'Sita Gufa, Nashik', lat: 20.008298, lng: 73.796333, info: 'Sacred cave in Panchavati' },
    { name: 'Sundarnarayan Temple, Nashik', lat: 20.006322, lng: 73.791559, info: 'Historic Vishnu temple near Ramkund' },
    { name: 'Kapaleshwar Temple, Nashik', lat: 20.007335, lng: 73.792881, info: 'Ancient Shiva temple near Ramkund' },
  ],
  hospitals: [
    { name: 'Civil Hospital Nashik', lat: 20.004921, lng: 73.778841, info: 'Hospital and emergency care' },
    { name: 'Apollo Hospital Nashik', lat: 20.004655, lng: 73.796115, info: 'Hospital and emergency care' },
    { name: 'Wockhardt Hospital Nashik', lat: 19.967520, lng: 73.771148, info: 'Hospital and emergency care' },
    { name: 'Trimbak Sub-District Hospital', lat: 19.936528, lng: 73.535805, info: 'Hospital and emergency care' },
    { name: 'Nashik District Hospital', lat: 20.004921, lng: 73.778841, info: 'Hospital and emergency care' },
  ],
  parking: [
    { name: 'Main parking near Ramkund', lat: 20.006500, lng: 73.790500, info: 'Parking near Ramkund' },
    { name: 'Parking near Trimbakeshwar Temple', lat: 19.936000, lng: 73.528500, info: 'Parking near Trimbakeshwar Temple' },
  ],
  transport: [
    { name: 'Nashik Road Railway Station', lat: 19.951525, lng: 73.834720, info: 'Railway station serving Nashik' },
    { name: 'Nashik City Railway Station', lat: 19.951525, lng: 73.834720, info: 'Railway station serving Nashik' },
    { name: 'CBS Bus Stand Nashik (Central Bus Station)', lat: 19.997200, lng: 73.778300, info: 'Main central bus station' },
    { name: 'Trimbakeshwar Bus Stand', lat: 19.936600, lng: 73.529800, info: 'Bus stand serving Trimbakeshwar' },
    { name: 'Mumbai Naka Bus Stop Nashik', lat: 19.988000, lng: 73.785000, info: 'Major bus stop in Nashik' },
  ],
  accommodation: [
    { name: 'Sadhugram Tapovan (Tent City area)', lat: 20.007300, lng: 73.804200, info: 'Pilgrim accommodation area' },
    { name: 'MTDC Resort Nashik', lat: 20.043500, lng: 73.682300, info: 'Accommodation near Nashik' },
  ],
  landmarks: [
    { name: 'Panchavati area center point', lat: 20.007500, lng: 73.795000, info: 'Center point for Panchavati' },
    { name: 'Tapovan, Nashik', lat: 20.004000, lng: 73.805500, info: 'Landmark in Nashik' },
    { name: 'Nashik city center', lat: 19.997500, lng: 73.789800, info: 'Center of Nashik city' },
  ],
};

/* ===== BREAKING NEWS TICKER ===== */
const TICKER_ITEMS = {
  en: [
    '🔔 First Shahi Snan on August 29, 2027 at Ramkund Ghat, Nashik',
    '🕉️ Free shuttle service between Nashik and Trimbakeshwar',
    '📢 Register for free accommodation at government dharamshalas',
    '⚠️ Carry identity proof for entry to restricted zones',
    '🚑 Emergency / Police: 112 | Ambulance: 108 | Nashik District Disaster Management: 1077',
    '🙏 Kumbh Mela Nashik 2027 — Jai Jai Gange!',
  ],
  hi: [
    '🔔 प्रथम शाही स्नान 29 अगस्त 2027 को रामकुंड घाट, नाशिक',
    '🕉️ नाशिक-त्र्यंबकेश्वर के बीच मुफ्त शटल सेवा',
    '📢 सरकारी धर्मशाला में मुफ्त ठहरने के लिए पंजीकरण करें',
    '⚠️ प्रतिबंधित क्षेत्रों में प्रवेश के लिए पहचान पत्र साथ रखें',
    '🚑 आपातकालीन / पुलिस: 112 | एम्बुलेंस: 108 | नाशिक जिला आपदा प्रबंधन: 1077',
    '🙏 कुंभ मेला नाशिक 2027 — जय जय गंगे!',
  ],
  mr: [
    '🔔 पहिले शाही स्नान 29 ऑगस्ट 2027 रोजी रामकुंड घाट, नाशिक',
    '🕉️ नाशिक-त्र्यंबकेश्वर दरम्यान मोफत शटल सेवा',
    '📢 सरकारी धर्मशाळेत मोफत राहण्यासाठी नोंदणी करा',
    '⚠️ प्रतिबंधित क्षेत्रात प्रवेशासाठी ओळखपत्र सोबत ठेवा',
    '🚑 आपत्कालीन / पोलीस: 112 | रुग्णवाहिका: 108 | नाशिक जिल्हा आपत्ती व्यवस्थापन: 1077',
    '🙏 कुंभ मेळा नाशिक 2027 — जय जय गंगे!',
  ],
};

/* ===== ABOUT KUMBH CONTENT ===== */
const ABOUT_CONTENT = {
  what_is_kumbh_en: `Kumbh Mela is the world's largest religious gathering, attended by hundreds of millions of pilgrims from across the globe. It is held at four sacred locations in India — Prayagraj, Haridwar, Nashik, and Ujjain — based on a rotation linked to the positions of Jupiter, the Sun, and the Moon in the zodiac.

The name "Kumbh" refers to the holy pitcher (kumbh/kalash) of nectar (amrit) that emerged during the churning of the cosmic ocean (Samudra Manthan). Drops of this nectar are believed to have fallen at these four locations, making them eternally sacred.

The origins of Kumbh Mela trace back thousands of years to the Vedic and Puranic traditions. It is mentioned in the Rig Veda and various Puranas. The current systematic form of Kumbh Mela is believed to have been organized by Adi Shankaracharya in the 8th century CE.`,
  what_is_kumbh_hi: `कुंभ मेला विश्व के सबसे बड़े धार्मिक समागमों में से एक है, जिसमें देश-दुनिया से करोड़ों श्रद्धालु आते हैं। यह भारत के चार पवित्र स्थलों — प्रयागराज, हरिद्वार, नाशिक और उज्जैन — में बृहस्पति, सूर्य और चंद्रमा की ज्योतिषीय स्थिति के अनुसार आयोजित होता है।

“कुंभ” अमृत से भरे उस पवित्र कलश को कहते हैं, जो समुद्र मंथन से निकला था। मान्यता है कि अमृत की बूंदें इन चार स्थानों पर गिरीं और इन्हें पवित्र बनाया।

कुंभ मेले की परंपरा वैदिक और पुराणिक काल से जुड़ी है। वर्तमान स्वरूप को 8वीं शताब्दी में आदि शंकराचार्य द्वारा व्यवस्थित किए जाने की मान्यता है।`,
  what_is_kumbh_mr: `कुंभमेळा हा जगातील सर्वात मोठ्या धार्मिक संमेलनांपैकी एक असून देश-विदेशातून कोट्यवधी भाविक येथे येतात. बृहस्पती, सूर्य आणि चंद्र यांच्या ज्योतिषीय स्थितीनुसार भारतातील प्रयागराज, हरिद्वार, नाशिक आणि उज्जैन या चार पवित्र ठिकाणी तो भरतो.

“कुंभ” म्हणजे समुद्रमंथनातून प्रकट झालेल्या अमृताचा पवित्र कलश. अमृताचे थेंब या चार ठिकाणी पडले आणि त्यामुळे ती पवित्र झाली, अशी श्रद्धा आहे.

कुंभमेळ्याची परंपरा वैदिक आणि पुराणिक काळापर्यंत जाते. आठव्या शतकात आदि शंकराचार्यांनी त्याला सध्याचे संघटित स्वरूप दिले, अशी मान्यता आहे.`,

  nashik_special_en: `Nashik, situated on the banks of the sacred Godavari river in Maharashtra, is one of the four Kumbh Mela sites. The Nashik Kumbh is also known as "Simhastha" and occurs when Jupiter is in Leo (Simha) and the Sun is in Aries (Mesh).

Trimbakeshwar, located 28km from Nashik, is the source of the Godavari river and home to one of the 12 sacred Jyotirlingas (divine light manifestations of Lord Shiva). The Shahi Snan at Nashik's Ramkund and Trimbakeshwar's Kushavart Kund are considered among the most purifying acts in Hindu religious tradition.

Nashik is also deeply connected to the Ramayana — it is the place where Lord Rama, Sita, and Lakshmana spent significant years of their 14-year exile at Panchavati. The sacred banyan trees at Panchavati still stand.`,
  nashik_special_hi: `महाराष्ट्र में पवित्र गोदावरी नदी के किनारे बसा नाशिक, कुंभ मेले के चार स्थलों में से एक है। इसे सिंहस्थ भी कहते हैं; यह तब आयोजित होता है जब बृहस्पति सिंह राशि में और सूर्य मेष राशि में होता है।

नाशिक से 28 किमी दूर त्र्यंबकेश्वर गोदावरी का उद्गम स्थल और भगवान शिव के 12 पवित्र ज्योतिर्लिंगों में से एक का स्थान है। नाशिक के Ramkund और त्र्यंबकेश्वर के Kushavart Kund में Shahi Snan को अत्यंत पवित्र माना जाता है।

नाशिक का रामायण से भी गहरा संबंध है। मान्यता है कि भगवान राम, सीता और लक्ष्मण ने अपने 14 वर्ष के वनवास का महत्वपूर्ण समय पंचवटी में बिताया था।`,
  nashik_special_mr: `महाराष्ट्रातील पवित्र गोदावरी नदीकाठी वसलेले नाशिक हे कुंभमेळ्याच्या चार स्थानांपैकी एक आहे. याला सिंहस्थ असेही म्हणतात. बृहस्पती सिंह राशीत आणि सूर्य मेष राशीत असताना हा मेळा भरतो.

नाशिकपासून 28 किमीवरील त्र्यंबकेश्वर हे गोदावरीचे उगमस्थान आणि भगवान शिवाच्या 12 पवित्र ज्योतिर्लिंगांपैकी एकाचे स्थान आहे. नाशिकच्या Ramkund आणि त्र्यंबकेश्वरच्या Kushavart Kund येथील Shahi Snan अत्यंत पवित्र मानले जाते.

नाशिकचा रामायणाशीही जवळचा संबंध आहे. भगवान राम, सीता आणि लक्ष्मण यांनी 14 वर्षांच्या वनवासातील महत्त्वाचा काळ पंचवटीत घालवला, अशी श्रद्धा आहे.`,

  shahi_significance_en: `The "Shahi Snan" (Royal Bath) is the most sacred and spectacular event of the Kumbh Mela. The word "Shahi" means royal, and these bathing processions involve elaborate, grand processions of akharas (monastic orders) with their saints, elephants, horses, and decorated chariots.

The timing of each Shahi Snan is determined by precise astronomical calculations based on the positions of the sun, moon, and Jupiter. Bathing at these specific times is believed to purify the soul of all sins accumulated over multiple lifetimes and to grant moksha (liberation from the cycle of rebirth).

The sequence of akharas in the Shahi Snan procession follows a strict historical order determined centuries ago. Witnessing or participating in the Shahi Snan is considered among the highest religious privileges in Hindu tradition.`,
  shahi_significance_hi: `Shahi Snan कुंभ मेले का सबसे पवित्र और भव्य आयोजन है। इसमें अखाड़ों के साधु-संत शोभायात्रा के साथ स्नान के लिए आते हैं; जुलूस में हाथी, घोड़े और सजे हुए रथ भी शामिल हो सकते हैं।

हर Shahi Snan का समय सूर्य, चंद्रमा और बृहस्पति की स्थिति के आधार पर तय किया जाता है। इस शुभ समय में स्नान को पापों से मुक्ति और मोक्ष की प्राप्ति से जोड़ा जाता है।

जुलूस में अखाड़ों का क्रम सदियों पुरानी परंपरा के अनुसार तय होता है। Shahi Snan को देखना या उसमें भाग लेना बड़ा धार्मिक सौभाग्य माना जाता है।`,
  shahi_significance_mr: `Shahi Snan हा कुंभमेळ्यातील सर्वात पवित्र आणि भव्य सोहळा आहे. आखाड्यांचे साधू-संत मिरवणुकीने स्नानासाठी येतात; मिरवणुकीत हत्ती, घोडे आणि सजवलेले रथही असू शकतात.

प्रत्येक Shahi Snan ची वेळ सूर्य, चंद्र आणि बृहस्पती यांच्या स्थितीनुसार ठरवली जाते. या शुभ वेळी स्नान केल्याने पापांपासून मुक्ती आणि मोक्ष मिळतो, अशी श्रद्धा आहे.

मिरवणुकीतील आखाड्यांचा क्रम शतकांपासून चालत आलेल्या परंपरेनुसार ठरतो. Shahi Snan पाहणे किंवा त्यात सहभागी होणे हा मोठा धार्मिक सन्मान मानला जातो.`,
};

/* ===== GALLERY IMAGES ===== */
const GALLERY_IMAGES = [
  { src: 'https://picsum.photos/seed/kumbh1/200/200', alt: 'Ghat at Nashik' },
  { src: 'https://picsum.photos/seed/kumbh2/200/200', alt: 'Ramkund Puja' },
  { src: 'https://picsum.photos/seed/kumbh3/200/200', alt: 'Trimbakeshwar Temple' },
  { src: 'https://picsum.photos/seed/kumbh4/200/200', alt: 'Akhara Procession' },
  { src: 'https://picsum.photos/seed/kumbh5/200/200', alt: 'Godavari River' },
  { src: 'https://picsum.photos/seed/kumbh6/200/200', alt: 'Devotees at Ghat' },
  { src: 'https://picsum.photos/seed/kumbh7/200/200', alt: 'Lamps at Ghat' },
  { src: 'https://picsum.photos/seed/kumbh8/200/200', alt: 'Sadhus at Kumbh' },
  { src: 'https://picsum.photos/seed/kumbh9/200/200', alt: 'Nashik Market' },
];
