/* ===================================================
   KumbhSathi — App Data
   All static data: events, listings, news, akharas,
   map markers, transport info, etc.
   Edit this file to update content.
   =================================================== */

/* ===== FIRST SHAHI SNAN DATE (countdown target) ===== */
const FIRST_SHAHI_SNAN_DATE = new Date('2027-08-29T05:30:00+05:30');

/* ===== SHAHI SNAN DATES ===== */
const SHAHI_SNAN_DATES = [
  {
    id: 'ss1',
    date: '2027-08-29',
    day: 29, month: 'Aug', year: 2027,
    tithi: 'श्रावण पूर्णिमा (Shravan Purnima)',
    title_en: 'First Shahi Snan — Niranjani Akhara & Anand Akhara',
    title_hi: 'प्रथम शाही स्नान — निरंजनी अखाड़ा',
    title_mr: 'पहिले शाही स्नान — निरंजनी आखाडा',
    location: 'Ramkund Ghat & Trimbakeshwar',
    time: '04:00 AM – 12:00 PM',
    significance_en: 'The first royal bath marks the beginning of the Simhastha Kumbh Mela. Niranjani and Anand Akharas take the holy dip first at Ramkund.',
    type: 'shahi',
  },
  {
    id: 'ss2',
    date: '2027-09-12',
    day: 12, month: 'Sep', year: 2027,
    tithi: 'भाद्रपद अमावस्या (Bhadrapad Amavasya)',
    title_en: 'Second Shahi Snan — Juna Akhara',
    title_hi: 'द्वितीय शाही स्नान — जूना अखाड़ा',
    title_mr: 'दुसरे शाही स्नान — जुना आखाडा',
    location: 'Ramkund Ghat, Nashik',
    time: '03:30 AM – 12:00 PM',
    significance_en: 'Juna Akhara, the largest akhara, performs the Shahi Snan on Bhadrapad Amavasya. Lakhs of devotees gather at Ramkund.',
    type: 'shahi',
  },
  {
    id: 'ss3',
    date: '2027-09-27',
    day: 27, month: 'Sep', year: 2027,
    tithi: 'महालया अमावस्या (Mahalaya Amavasya)',
    title_en: 'Third Shahi Snan — Mahanirvani & Atal Akhara',
    title_hi: 'तृतीय शाही स्नान — महानिर्वाणी अखाड़ा',
    title_mr: 'तिसरे शाही स्नान — महानिर्वाणी आखाडा',
    location: 'Ramkund, Nashik & Kushavart Kund, Trimbakeshwar',
    time: '04:00 AM – 01:00 PM',
    significance_en: 'The third and final major Shahi Snan during Simhastha. All akharas participate in this grand event at Ramkund.',
    type: 'shahi',
  },
];

/* ===== EVENTS (Schedule page) ===== */
const EVENTS_DATA = [
  ...SHAHI_SNAN_DATES,
  {
    id: 'ev1',
    date: '2027-08-01',
    day: 1, month: 'Aug', year: 2027,
    tithi: 'सिंहस्थ कुंभ उद्घाटन',
    title_en: 'Official Inauguration of Simhastha Kumbh Mela',
    title_hi: 'सिंहस्थ कुंभ मेले का आधिकारिक उद्घाटन',
    title_mr: 'सिंहस्थ कुंभ मेळ्याचे अधिकृत उद्घाटन',
    location: 'Ramkund Ground, Nashik',
    time: '10:00 AM',
    significance_en: 'Grand inauguration ceremony with Puja, procession of Akharas and cultural programs. VIP dignitaries and saints to be present.',
    type: 'religious',
  },
  {
    id: 'ev2',
    date: '2027-08-05',
    day: 5, month: 'Aug', year: 2027,
    tithi: 'श्रावण पंचमी',
    title_en: 'Naga Sadhu Procession — Peshwai',
    title_hi: 'नागा साधु जुलूस — पेशवाई',
    title_mr: 'नागा साधू मिरवणूक — पेशवाई',
    location: 'Main Road Nashik → Ramkund',
    time: '08:00 AM – 02:00 PM',
    significance_en: 'Spectacular procession of Naga Sadhus, elephants, horses, and decorated chariots through the streets of Nashik.',
    type: 'cultural',
  },
  {
    id: 'ev3',
    date: '2027-08-15',
    day: 15, month: 'Aug', year: 2027,
    tithi: 'स्वतंत्रता दिवस',
    title_en: 'Independence Day Special Puja & Cultural Night',
    title_hi: 'स्वतंत्रता दिवस विशेष पूजा और सांस्कृतिक संध्या',
    title_mr: 'स्वातंत्र्य दिन विशेष पूजा व सांस्कृतिक संध्या',
    location: 'Ramkund Amphitheater',
    time: '06:00 PM – 10:00 PM',
    significance_en: 'Special Independence Day celebration at the Kumbh grounds with classical music, folk dances, and patriotic performances.',
    type: 'cultural',
  },
  {
    id: 'ev4',
    date: '2027-08-20',
    day: 20, month: 'Aug', year: 2027,
    tithi: 'श्रावण शिवरात्रि',
    title_en: 'Shravan Shivratri — Rudrabhishek',
    title_hi: 'श्रावण शिवरात्रि — रुद्राभिषेक',
    title_mr: 'श्रावण शिवरात्री — रुद्राभिषेक',
    location: 'Trimbakeshwar Mandir, Trimbakeshwar',
    time: '12:00 AM – 06:00 AM',
    significance_en: 'Grand Rudrabhishek at Trimbakeshwar Temple with 108 priests. One of the most auspicious nights of the Kumbh.',
    type: 'religious',
  },
  {
    id: 'ev5',
    date: '2027-09-01',
    day: 1, month: 'Sep', year: 2027,
    tithi: 'भाद्रपद प्रथमा',
    title_en: 'Ganesh Utsav Celebrations at Kumbh',
    title_hi: 'गणेश उत्सव समारोह',
    title_mr: 'गणेशोत्सव सोहळा',
    location: 'Kumbh Cultural Stage, Nashik',
    time: '04:00 PM – 11:00 PM',
    significance_en: 'Kumbh Mela special Ganesh Utsav with classical and folk performances, bringing Maharashtra\'s greatest festival to the holy grounds.',
    type: 'cultural',
  },
  {
    id: 'ev6',
    date: '2027-09-10',
    day: 10, month: 'Sep', year: 2027,
    tithi: 'पितृ पक्ष आरंभ',
    title_en: 'Pitru Paksha Begins — Tarpan at Ramkund',
    title_hi: 'पितृ पक्ष आरंभ — रामकुंड पर तर्पण',
    title_mr: 'पितृपक्ष प्रारंभ — रामकुंड तर्पण',
    location: 'Ramkund, Nashik',
    time: '06:00 AM – 12:00 PM',
    significance_en: 'Sacred Tarpan rituals for ancestors at Ramkund. Nashik is one of the most holy places for Pitru Paksha ceremonies.',
    type: 'religious',
  },
  {
    id: 'ev7',
    date: '2027-10-05',
    day: 5, month: 'Oct', year: 2027,
    tithi: 'विजयादशमी (दशहरा)',
    title_en: 'Vijaya Dashami — Kumbh Closing Ceremony',
    title_hi: 'विजयादशमी — कुंभ समापन समारोह',
    title_mr: 'विजयादशमी — कुंभ समारोप सोहळा',
    location: 'Ramkund Ground, Nashik',
    time: '10:00 AM – 06:00 PM',
    significance_en: 'Grand closing ceremony of Simhastha Kumbh Mela on Vijayadashami with final Shahi processions and ceremonial farewell.',
    type: 'religious',
  },
];

/* ===== STAY LISTINGS ===== */
const STAY_DATA = [
  {
    id: 'st1',
    name: 'Hotel Sai Heritage',
    type: 'Hotel',
    category: 'premium',
    price: '₹3,500 – ₹7,000',
    distance: '0.5 km from Ramkund',
    contact: '+91 98765 43210',
    rating: 4.5,
    sponsored: true,
    description: 'Luxury hotel with AC rooms, restaurant, rooftop view of Godavari river. Special Kumbh packages available.',
    facilities: ['AC', 'Restaurant', 'WiFi', 'Parking'],
    image: 'https://picsum.photos/seed/hotel1/300/180',
  },
  {
    id: 'st2',
    name: 'Kumbh Grand Resort',
    type: 'Resort',
    category: 'premium',
    price: '₹4,000 – ₹9,000',
    distance: '1.2 km from Ramkund',
    contact: '+91 98765 43211',
    rating: 4.8,
    sponsored: true,
    description: 'Premium resort with all modern amenities, swimming pool, and dedicated Kumbh concierge service.',
    facilities: ['AC', 'Pool', 'Restaurant', 'Spa', 'WiFi'],
    image: 'https://picsum.photos/seed/hotel2/300/180',
  },
  {
    id: 'st3',
    name: 'Trimbakeshwar Ashram Stay',
    type: 'Ashram',
    category: 'dharam',
    price: 'Free / Donation',
    distance: '0.2 km from Trimbakeshwar Temple',
    contact: '+91 97654 32109',
    rating: 4.2,
    sponsored: false,
    description: 'Traditional ashram accommodation with vegetarian meals, yoga, and spiritual programs. Donation-based.',
    facilities: ['Meals Included', 'Yoga', 'Meditation'],
    image: 'https://picsum.photos/seed/ashram1/300/180',
  },
  {
    id: 'st4',
    name: 'Nashik Dharamshala',
    type: 'Dharamshala',
    category: 'dharam',
    price: '₹200 – ₹400',
    distance: '0.8 km from Ramkund',
    contact: '+91 96543 21098',
    rating: 3.8,
    sponsored: false,
    description: 'Affordable dharamshala with basic facilities. Suitable for families and pilgrims. Clean and safe.',
    facilities: ['Common Bathrooms', 'Safe Lockers'],
    image: 'https://picsum.photos/seed/dharam1/300/180',
  },
  {
    id: 'st5',
    name: 'Hotel Panchavati Inn',
    type: 'Hotel',
    category: 'mid',
    price: '₹1,200 – ₹2,500',
    distance: '0.3 km from Ramkund',
    contact: '+91 95432 10987',
    rating: 4.0,
    sponsored: true,
    description: 'Mid-range hotel centrally located near Panchavati and Ramkund. Great value for Kumbh pilgrims.',
    facilities: ['AC Available', 'Restaurant', 'Parking'],
    image: 'https://picsum.photos/seed/hotel3/300/180',
  },
  {
    id: 'st6',
    name: 'Godavari Guest House',
    type: 'Guest House',
    category: 'budget',
    price: '₹600 – ₹1,000',
    distance: '0.4 km from Ramkund',
    contact: '+91 94321 09876',
    rating: 3.5,
    sponsored: false,
    description: 'Budget-friendly guest house with clean rooms, attached bathroom. River view from some rooms.',
    facilities: ['Hot Water', 'Fan Rooms', 'Parking'],
    image: 'https://picsum.photos/seed/guesthouse1/300/180',
  },
  {
    id: 'st7',
    name: 'Kumbh Tent City (Government)',
    type: 'Tent Camp',
    category: 'budget',
    price: '₹500 – ₹1,500',
    distance: '1.0 km from Ramkund',
    contact: '+91 93210 98765',
    rating: 3.9,
    sponsored: false,
    description: 'Official government-run tent city with basic amenities. Shared bathrooms and common dining.',
    facilities: ['Shared Bathrooms', 'Meals', 'Security'],
    image: 'https://picsum.photos/seed/tent1/300/180',
  },
  {
    id: 'st8',
    name: 'Om Shanti Dharamshala',
    type: 'Dharamshala',
    category: 'dharam',
    price: 'Free (Registration Required)',
    distance: '0.6 km from Ramkund',
    contact: '+91 92109 87654',
    rating: 4.1,
    sponsored: false,
    description: 'Free accommodation for genuine pilgrims. Vegetarian sattvic food available. Prior registration needed.',
    facilities: ['Free Meals', 'Puja Hall', 'Safe Lockers'],
    image: 'https://picsum.photos/seed/dharam2/300/180',
  },
  {
    id: 'st9',
    name: 'Hotel Trimbak Palace',
    type: 'Hotel',
    category: 'mid',
    price: '₹1,800 – ₹3,000',
    distance: '0.3 km from Trimbakeshwar Temple',
    contact: '+91 91098 76543',
    rating: 4.3,
    sponsored: false,
    description: 'Well-appointed hotel near Trimbakeshwar Temple with modern amenities and excellent service.',
    facilities: ['AC', 'Restaurant', 'WiFi', 'Parking'],
    image: 'https://picsum.photos/seed/hotel4/300/180',
  },
  {
    id: 'st10',
    name: 'Sadguru Ashram & Guest House',
    type: 'Ashram',
    category: 'budget',
    price: '₹300 – ₹600',
    distance: '1.5 km from Ramkund',
    contact: '+91 90987 65432',
    rating: 4.0,
    sponsored: false,
    description: 'Spiritual ashram with simple accommodation, daily satsang, and nutritious vegetarian meals.',
    facilities: ['Meals', 'Satsang Hall', 'Yoga'],
    image: 'https://picsum.photos/seed/ashram2/300/180',
  },
  {
    id: 'st11',
    name: 'Hotel Panorama Nashik',
    type: 'Hotel',
    category: 'premium',
    price: '₹5,000 – ₹12,000',
    distance: '2.0 km from Ramkund',
    contact: '+91 89876 54321',
    rating: 4.7,
    sponsored: false,
    description: 'Luxury 4-star hotel with panoramic views, rooftop restaurant, and exclusive Kumbh packages for VIP guests.',
    facilities: ['AC', 'Pool', 'Restaurant', 'Gym', 'Spa', 'WiFi'],
    image: 'https://picsum.photos/seed/hotel5/300/180',
  },
];

/* ===== NEWS DATA ===== */
const NEWS_DATA = [
  {
    id: 'n1',
    category: 'announce',
    headline_en: 'Nashik Kumbh 2027: Government Announces ₹5,000 Crore Infrastructure Plan',
    headline_hi: 'नाशिक कुंभ 2027: सरकार ने ₹5,000 करोड़ के बुनियादी ढांचे की घोषणा की',
    headline_mr: 'नाशिक कुंभ 2027: सरकारने ₹5,000 कोटी पायाभूत सुविधांची घोषणा केली',
    date: '15 Jan 2027',
    short_en: 'Maharashtra government approves a massive ₹5,000 crore infrastructure plan for Nashik and Trimbakeshwar to handle the unprecedented crowd during Simhastha Kumbh 2027.',
    full_en: 'Maharashtra government has approved a massive ₹5,000 crore infrastructure development plan for Nashik and Trimbakeshwar ahead of Simhastha Kumbh Mela 2027. The plan includes construction of 8 new ghats, widening of 45 roads, installation of 10,000 CCTV cameras, 50 new parking zones, and a state-of-the-art crowd monitoring system. Chief Minister confirmed that over 5 crore pilgrims are expected during the 3-month event.',
    image: 'https://picsum.photos/seed/news1/200/130',
  },
  {
    id: 'n2',
    category: 'vip',
    headline_en: 'Prime Minister to Attend Inauguration of Nashik Kumbh 2027',
    headline_hi: 'प्रधानमंत्री नाशिक कुंभ 2027 के उद्घाटन में शामिल होंगे',
    headline_mr: 'पंतप्रधान नाशिक कुंभ 2027 च्या उद्घाटनाला उपस्थित राहणार',
    date: '28 Feb 2027',
    short_en: 'Prime Minister confirmed to inaugurate the Simhastha Kumbh Mela 2027 at Nashik on August 1st, 2027 along with religious leaders and Chief Minister.',
    full_en: 'The Prime Minister of India has confirmed attendance at the official inauguration of Simhastha Kumbh Mela 2027 at Nashik on August 1st. The event will be attended by the Chief Minister of Maharashtra, Union Ministers, and prominent saints and religious leaders from across India. A grand cultural program featuring artists from all 28 states has been planned. Security arrangements for the VIP visit are being coordinated by NSG and state police.',
    image: 'https://picsum.photos/seed/news2/200/130',
  },
  {
    id: 'n3',
    category: 'weather',
    headline_en: 'IMD Forecast: Normal Monsoon Expected During Nashik Kumbh Period',
    headline_hi: 'IMD पूर्वानुमान: नाशिक कुंभ के दौरान सामान्य मानसून की उम्मीद',
    headline_mr: 'IMD अंदाज: नाशिक कुंभ काळात सामान्य पाऊस अपेक्षित',
    date: '10 Mar 2027',
    short_en: 'India Meteorological Department forecasts normal monsoon rainfall during the Nashik Kumbh period. Pilgrims advised to carry light rain gear.',
    full_en: 'India Meteorological Department (IMD) has released its forecast indicating normal monsoon rainfall patterns for the Nashik region during the August-September 2027 Kumbh period. Average rainfall of 80-100mm per month is expected. While rainfall during Shahi Snan days may occur, authorities are well-prepared. Pilgrims are advised to carry lightweight rain gear and check weather updates regularly. Emergency shelters are being set up at all major ghat points.',
    image: 'https://picsum.photos/seed/news3/200/130',
  },
  {
    id: 'n4',
    category: 'announce',
    headline_en: 'Free Shuttle Service Between Nashik and Trimbakeshwar During Kumbh',
    headline_hi: 'कुंभ के दौरान नाशिक और त्र्यंबकेश्वर के बीच मुफ्त शटल सेवा',
    headline_mr: 'कुंभ काळात नाशिक व त्र्यंबकेश्वर दरम्यान मोफत शटल सेवा',
    date: '5 Apr 2027',
    short_en: 'Maharashtra MSRTC announces free shuttle bus service connecting Nashik and Trimbakeshwar every 15 minutes throughout the Kumbh Mela period.',
    full_en: 'Maharashtra State Road Transport Corporation (MSRTC) has announced a free shuttle bus service connecting Nashik city and Trimbakeshwar throughout the Simhastha Kumbh Mela 2027. Buses will operate every 15 minutes from 4 AM to midnight. Special buses for elderly and differently-abled pilgrims will be available. Over 500 buses have been dedicated for this service. The shuttle will operate from Nashik Bus Stand, Panchavati, Ramkund, and all major akhara camps.',
    image: 'https://picsum.photos/seed/news4/200/130',
  },
  {
    id: 'n5',
    category: 'traffic',
    headline_en: 'Traffic Diversion Plan Released for Nashik City During Shahi Snan Days',
    headline_hi: 'शाही स्नान के दिनों के लिए नाशिक में यातायात डायवर्जन योजना जारी',
    headline_mr: 'शाही स्नानाच्या दिवसांसाठी नाशिकमध्ये वाहतूक बदल योजना जाहीर',
    date: '20 May 2027',
    short_en: 'Nashik Police releases detailed traffic diversion plan for Shahi Snan days. Private vehicles to be restricted within 5km of Ramkund.',
    full_en: 'Nashik Police has released a detailed traffic management and diversion plan for the three Shahi Snan days during Simhastha Kumbh 2027. Private vehicles will be restricted within a 5km radius of Ramkund Ghat on Shahi Snan days. 45 parking zones have been designated at various points across Nashik. Park-and-walk, park-and-shuttle facilities are available. Out-of-state vehicles arriving via Highway NH3 and NH60 will be directed to designated parking areas.',
    image: 'https://picsum.photos/seed/news5/200/130',
  },
  {
    id: 'n6',
    category: 'announce',
    headline_en: '50,000 Security Personnel to Be Deployed for Nashik Kumbh 2027',
    headline_hi: 'नाशिक कुंभ 2027 के लिए 50,000 सुरक्षाकर्मी तैनात होंगे',
    headline_mr: 'नाशिक कुंभ 2027 साठी 50,000 सुरक्षा जवान तैनात होणार',
    date: '1 Jun 2027',
    short_en: 'Maharashtra Home Department approves deployment of 50,000 police and security personnel including CRPF companies for Kumbh security.',
    full_en: 'The Maharashtra Home Department has approved deployment of 50,000 police and security personnel for Simhastha Kumbh Mela 2027. This includes state police, CRPF companies, NSG for VIP protection, fire brigade teams, and 5,000 home guards. AI-powered crowd monitoring systems will be installed at 50 strategic points. Lost and found centers will operate at 10 locations. A dedicated control room will coordinate all emergency responses.',
    image: 'https://picsum.photos/seed/news6/200/130',
  },
  {
    id: 'n7',
    category: 'vip',
    headline_en: 'Spiritual Leaders from 12 Countries to Attend Nashik Kumbh 2027',
    headline_hi: '12 देशों के आध्यात्मिक नेता नाशिक कुंभ 2027 में शामिल होंगे',
    headline_mr: '12 देशांतील अध्यात्मिक नेते नाशिक कुंभ 2027 ला उपस्थित राहणार',
    date: '15 Jun 2027',
    short_en: 'Spiritual leaders, sadhus, and delegations from 12 countries including USA, UK, Germany, Japan, and Australia to attend Nashik Kumbh.',
    full_en: 'The Ministry of External Affairs has confirmed participation of spiritual leaders and cultural delegations from 12 countries at Simhastha Kumbh Mela Nashik 2027. Delegations from USA, UK, Germany, France, Japan, Australia, Singapore, South Africa, Brazil, Canada, Nepal, and Sri Lanka will be present. Special arrangements for international pilgrims including translation services, international food options, and dedicated accommodation zones are being prepared.',
    image: 'https://picsum.photos/seed/news7/200/130',
  },
  {
    id: 'n8',
    category: 'announce',
    headline_en: 'KumbhSathi App Launched: Digital Guide for Nashik Kumbh Pilgrims',
    headline_hi: 'कुंभसाथी ऐप लॉन्च: नाशिक कुंभ यात्रियों के लिए डिजिटल गाइड',
    headline_mr: 'कुंभसाथी ऐप लॉन्च: नाशिक कुंभ भाविकांसाठी डिजिटल मार्गदर्शक',
    date: '1 Jul 2027',
    short_en: 'Official KumbhSathi mobile app launched to help pilgrims navigate Nashik Kumbh 2027 with maps, schedules, emergency contacts, and lost & found services.',
    full_en: 'The KumbhSathi mobile application has been officially launched as the comprehensive digital companion for pilgrims attending Simhastha Kumbh Mela Nashik 2027. The app features interactive maps with OpenStreetMap, complete event schedules, accommodation listings, transport guides, emergency helplines, and a lost & found reporting system. Available in English, Hindi, and Marathi. The app works offline and is available as a Progressive Web App installable on any smartphone.',
    image: 'https://picsum.photos/seed/news8/200/130',
  },
];

/* ===== AKHARAS DATA ===== */
const AKHARAS_DATA = [
  {
    id: 'ak1',
    name: 'श्री पंचायती अखाड़ा महानिर्वाणी',
    name_en: 'Mahanirvani Akhara',
    type: 'शैव (Shaiva)',
    camp: 'Panchavati Camp Ground, Nashik',
    deity: 'Lord Shiva (Kapila)',
    est: 'Est. 8th century CE',
    desc_hi: 'यह सबसे प्राचीन और सम्मानित अखाड़ों में से एक है। इसकी स्थापना आदि गुरु शंकराचार्य ने की थी। महानिर्वाणी अखाड़ा शाही स्नान में प्रथम स्थान प्राप्त करने वाला अखाड़ा है।',
    desc_en: 'One of the oldest and most revered Shaiva akharas, founded by Adi Guru Shankaracharya. Mahanirvani Akhara holds the first position in the Shahi Snan procession.',
    icon: '🕉️',
  },
  {
    id: 'ak2',
    name: 'श्री पंचदशनाम जूना अखाड़ा',
    name_en: 'Juna Akhara',
    type: 'शैव — नागा (Shaiva Naga)',
    camp: 'Godavari Camp Area, Nashik',
    deity: 'Lord Dattatreya',
    est: 'Est. 13th century CE',
    desc_hi: 'जूना अखाड़ा सबसे बड़ा और सबसे प्रसिद्ध अखाड़ा है। इसमें 5 लाख से अधिक साधु सदस्य हैं। नागा साधुओं की अनूठी परंपराओं के लिए जाना जाता है।',
    desc_en: 'Juna Akhara is the largest akhara with over 5 lakh member sadhus. Famous for its Naga Sadhus and unique spiritual traditions. Also known as Bhairav Akhara.',
    icon: '🔱',
  },
  {
    id: 'ak3',
    name: 'श्री पंचायती अखाड़ा निरंजनी',
    name_en: 'Niranjani Akhara',
    type: 'शैव (Shaiva)',
    camp: 'Ramkund Camp, Nashik',
    deity: 'Lord Kartik',
    est: 'Est. 904 CE',
    desc_hi: 'निरंजनी अखाड़ा शाही स्नान में दूसरे स्थान पर है। इसकी स्थापना 904 CE में हुई। यह अखाड़ा सात प्रमुख शैव अखाड़ों में से एक है।',
    desc_en: 'Niranjani Akhara holds the second position in Shahi Snan. Founded in 904 CE, it is one of the seven major Shaiva akharas and is known for its scholarly traditions.',
    icon: '☀️',
  },
  {
    id: 'ak4',
    name: 'श्री पंचायती अटल अखाड़ा',
    name_en: 'Atal Akhara',
    type: 'शैव (Shaiva)',
    camp: 'Trimbakeshwar Camp',
    deity: 'Lord Ganesha',
    est: 'Est. 569 CE',
    desc_hi: 'अटल अखाड़ा सबसे छोटे पंच अखाड़ों में से एक है। लेकिन इसकी परंपराएं बेहद प्राचीन हैं। भगवान गणेश इस अखाड़े के इष्ट देव हैं।',
    desc_en: 'Atal Akhara, though one of the smaller akharas, has ancient traditions dating back to 569 CE. Lord Ganesha is the presiding deity. Known for its Vedic scholarship.',
    icon: '🐘',
  },
  {
    id: 'ak5',
    name: 'श्री निर्मल पंचायती अखाड़ा',
    name_en: 'Nirmal Akhara',
    type: 'सिख (Sikh)',
    camp: 'Nashik Camp Zone B',
    deity: 'Guru Granth Sahib',
    est: 'Est. 1784 CE',
    desc_hi: 'निर्मल अखाड़ा सिख परंपरा का प्रतिनिधित्व करता है। इसकी स्थापना 1784 CE में दसवें गुरु की आज्ञा से हुई। यह कुंभ में सिख-हिंदू एकता का प्रतीक है।',
    desc_en: 'Nirmal Akhara represents the Sikh tradition at Kumbh, founded in 1784 CE. It is a symbol of Sikh-Hindu unity and participates in all Kumbh rituals alongside Shaiva and Vaishnava akharas.',
    icon: '✡️',
  },
  {
    id: 'ak6',
    name: 'श्री वैष्णव दिगंबर अखाड़ा',
    name_en: 'Digambar Akhara (Vaishnava)',
    type: 'वैष्णव (Vaishnava)',
    camp: 'Godavari Bank Camp, Nashik',
    deity: 'Lord Vishnu',
    est: 'Est. Ancient',
    desc_hi: 'दिगंबर अखाड़ा वैष्णव संप्रदाय का प्रमुख अखाड़ा है। भगवान विष्णु के भक्त साधुओं का यह संगम भारत की अद्वितीय धार्मिक परंपराओं को जीवंत रखता है।',
    desc_en: 'Digambar Akhara is a prominent Vaishnava akhara devoted to Lord Vishnu. Represents the Vaishnava sampradaya tradition and participates in Vaishnava Shahi Snan at Ramkund.',
    icon: '🌺',
  },
  {
    id: 'ak7',
    name: 'श्री पंचायती उदासीन अखाड़ा (बड़ा)',
    name_en: 'Bada Udaseen Akhara',
    type: 'उदासीन (Udaseen)',
    camp: 'Nashik Camp Zone C',
    deity: 'Lord Ram & Shiva',
    est: 'Est. 17th century',
    desc_hi: 'उदासीन संप्रदाय की स्थापना श्री चंद्र जी महाराज ने की थी। यह अखाड़ा गुरु नानक के पुत्र श्री चंद्र की परंपरा को आगे बढ़ाता है।',
    desc_en: 'Founded in the Udaseen tradition by Sri Chandra Ji Maharaj, son of Guru Nanak. This akhara bridges Sikh and Hindu traditions and participates actively in Kumbh Mela.',
    icon: '🕊️',
  },
];

/* ===== TRANSPORT DATA ===== */
const TRANSPORT_DATA = {
  byTrain: [
    {
      route: 'Mumbai → Nashik Road Station',
      duration: '~3 hours',
      cost: '₹150 – ₹600 (Class dependent)',
      trains: ['Panchavati Express', 'Tapovan Express', 'Mumbai-Manmad Passenger'],
      info: 'Nashik Road is the main railway station, 8km from city centre. Frequent trains from CSMT, Dadar, Kalyan.',
    },
    {
      route: 'Pune → Nashik Road',
      duration: '~4 hours',
      cost: '₹200 – ₹700',
      trains: ['Nashik Express', 'Intercity Express'],
      info: 'Change at Manmad or direct trains available. Check IRCTC for special Kumbh trains.',
    },
    {
      route: 'Aurangabad → Nashik Road',
      duration: '~3.5 hours',
      cost: '₹150 – ₹550',
      trains: ['Intercity services', 'Passenger trains'],
      info: 'Via Manmad Junction. Several daily connections available.',
    },
  ],
  byBus: [
    {
      route: 'Mumbai → Nashik',
      duration: '~4-5 hours',
      cost: '₹200 – ₹500 (AC/Non-AC)',
      operator: 'MSRTC, Private Volvo buses',
      info: 'Buses depart from Dadar, Borivali, Thane, and CSMT. Every 30 minutes during Kumbh peak.',
    },
    {
      route: 'Pune → Nashik',
      duration: '~4-5 hours',
      cost: '₹250 – ₹600',
      operator: 'MSRTC, Private operators',
      info: 'Multiple buses daily. Book in advance during Kumbh peak season.',
    },
    {
      route: 'Aurangabad → Nashik',
      duration: '~3 hours',
      cost: '₹180 – ₹400',
      operator: 'MSRTC',
      info: 'Frequent service. Via Yeola junction.',
    },
  ],
  byAir: [
    {
      airport: 'Nashik Airport (Ozar)',
      dist: '20 km from Nashik city',
      flights: 'Mumbai, Hyderabad, Bengaluru',
      info: 'Ozar Airport has limited commercial flights. During Kumbh, special flights may be added. Check airlines for latest schedules.',
    },
    {
      airport: 'Pune Airport (PNQ)',
      dist: '210 km from Nashik',
      info: 'Nearest major airport. Well-connected internationally. Take bus/taxi from Pune to Nashik (4-5 hrs).',
    },
    {
      airport: 'Chhatrapati Shivaji Maharaj (BOM)',
      dist: '170 km from Nashik',
      info: 'Mumbai Airport — best connected internationally. Multiple transport options to Nashik: bus, train, cab.',
    },
  ],
  byRoad: [
    {
      route: 'Mumbai → Nashik',
      highway: 'NH-160 (Kasara Ghat) or NH-61 (Bhiwandi-Igatpuri)',
      duration: '~3.5 – 4.5 hours',
      dist: '~170 km',
      info: 'NH-160 is the main route via Kasara. NH-61 via Bhiwandi-Igatpuri is more scenic but slower.',
    },
    {
      route: 'Pune → Nashik',
      highway: 'NH-60 (via Shirdi) or via Sangamner',
      duration: '~4 – 5 hours',
      dist: '~210 km',
      info: 'NH-60 via Shirdi is the fastest route. Via Sangamner adds extra 30 min but avoids highway tolls.',
    },
    {
      route: 'Aurangabad → Nashik',
      highway: 'NH-752C via Yeola',
      duration: '~3 hours',
      dist: '~105 km',
      info: 'Good quality road. Route passes through Yeola, famous for its handwoven Paithani sarees.',
    },
  ],
  local: [
    {
      mode: 'Free Shuttle Bus',
      icon: 'fa-bus',
      route: 'Nashik Bus Stand ↔ Ramkund ↔ Trimbakeshwar',
      frequency: 'Every 15 minutes (4 AM – 12 AM)',
      cost: 'FREE during Kumbh',
    },
    {
      mode: 'Auto Rickshaw',
      icon: 'fa-taxi',
      route: 'Anywhere in Nashik city',
      frequency: 'On demand (pre-paid counter at station)',
      cost: '₹30 minimum, ₹15/km after 1.5km',
    },
    {
      mode: 'City Bus (MSRTC)',
      icon: 'fa-bus',
      route: 'Routes 1–32 covering all major areas',
      frequency: 'Every 10-15 min on main routes',
      cost: '₹10 – ₹25 flat fare during Kumbh',
    },
    {
      mode: 'Nashik → Trimbakeshwar',
      icon: 'fa-van-shuttle',
      route: 'Direct: 28 km distance',
      frequency: 'Shuttle every 15 min / Cab on demand',
      cost: 'Free shuttle / ₹400-600 cab (shared: ₹80-100)',
    },
  ],
};

/* ===== HOSPITALS DATA ===== */
const HOSPITALS_DATA = [
  { name: 'Civil Hospital Nashik', addr: 'Near CBS, Nashik', phone: '0253-2577000', emergency: true },
  { name: 'Wockhardt Hospital', addr: 'Gangapur Rd, Nashik', phone: '0253-6604444', emergency: true },
  { name: 'Trimbak General Hospital', addr: 'Main Rd, Trimbakeshwar', phone: '02594-233244', emergency: true },
  { name: 'Nashik Civil Trauma Centre', addr: 'Nashik Road', phone: '0253-2464000', emergency: true },
  { name: 'Kumbh Medical Camp', addr: 'Ramkund Camp, Nashik', phone: '1800-XXX-XXXX (Toll Free)', emergency: true },
];

/* ===== FIRST AID TIPS ===== */
const FIRST_AID_DATA = [
  {
    title_en: 'Heat Stroke & Dehydration',
    title_hi: 'लू और निर्जलीकरण',
    tips_en: [
      'Move the person to shade immediately',
      'Give ORS / cold water to drink slowly',
      'Apply wet cloth on head and neck',
      'Fan the person to cool down body',
      'Seek medical help if unconscious',
    ],
  },
  {
    title_en: 'Crowd Crush / Stampede',
    title_hi: 'भीड़ में दबना',
    tips_en: [
      'Don\'t panic — move with the crowd flow',
      'Keep arms bent at elbow to protect chest',
      'If down, curl into a ball and protect head',
      'Call out loudly for help',
      'Move to sides, not against the crowd',
    ],
  },
  {
    title_en: 'Getting Lost at Kumbh',
    title_hi: 'भीड़ में खो जाने पर',
    tips_en: [
      'Call Kumbh Control Room: 1800-XXX-XXXX',
      'Go to nearest Police Booth',
      'Stay at a landmark — don\'t wander',
      'Use the KumbhSathi Lost & Found feature',
      'Share your location with family',
    ],
  },
  {
    title_en: 'Snake Bite',
    title_hi: 'सर्पदंश',
    tips_en: [
      'Keep the bitten area still and below heart level',
      'Do NOT suck, cut, or apply tourniquet',
      'Remove jewelry/tight clothing near bite',
      'Note time of bite and snake appearance',
      'Rush to nearest hospital immediately — call 108',
    ],
  },
  {
    title_en: 'Drowning / Water Accident',
    title_hi: 'डूबने की स्थिति में',
    tips_en: [
      'Call 100 or 108 immediately',
      'Don\'t jump into water if untrained',
      'Throw a rope or floating object',
      'Once out, lay person on side to drain water',
      'Begin CPR if not breathing — call 108',
    ],
  },
];

/* ===== MAP MARKERS ===== */
const MAP_MARKERS = {
  ghats: [
    { name: 'Ramkund Ghat', lat: 20.0032, lng: 73.7891, info: 'Most sacred ghat — main Shahi Snan location' },
    { name: 'Kushavart Kund', lat: 19.9322, lng: 73.5308, info: 'Main ghat at Trimbakeshwar for Shahi Snan' },
    { name: 'Someshwar Ghat', lat: 20.0089, lng: 73.7944, info: 'Popular ghat for daily ritual baths' },
    { name: 'Holkar Bridge Ghat', lat: 19.9998, lng: 73.7921, info: 'Ghat near Holkar Bridge, Godavari river' },
  ],
  temples: [
    { name: 'Trimbakeshwar Jyotirlinga', lat: 19.9322, lng: 73.5308, info: 'One of 12 Jyotirlingas — most sacred temple of Kumbh' },
    { name: 'Kapaleshwar Temple', lat: 20.0031, lng: 73.7889, info: 'Ancient Shiva temple at Ramkund' },
    { name: 'Sundernarayan Temple', lat: 20.0028, lng: 73.7883, info: 'Beautiful Vishnu temple near Ramkund' },
    { name: 'Muktidhaam Temple', lat: 20.0209, lng: 73.8174, info: 'Marble replica of 12 Jyotirlingas' },
    { name: 'Kalaram Temple', lat: 19.9956, lng: 73.7899, info: 'Famous Ram temple in Panchavati' },
  ],
  camps: [
    { name: 'Juna Akhara Camp', lat: 20.0018, lng: 73.7865, info: 'Camp of Juna Akhara — largest akhara at Kumbh' },
    { name: 'Niranjani Akhara Camp', lat: 20.0041, lng: 73.7898, info: 'Camp of Niranjani Akhara' },
    { name: 'Mahanirvani Akhara Camp', lat: 19.9995, lng: 73.7856, info: 'Camp of Mahanirvani Akhara' },
    { name: 'Peshwai Ground', lat: 20.0062, lng: 73.7925, info: 'Main procession ground for Peshwai ceremonies' },
  ],
  hospitals: [
    { name: 'Civil Hospital Nashik', lat: 19.9978, lng: 73.7813, info: '24/7 Emergency — 0253-2577000' },
    { name: 'Kumbh Medical Camp (Main)', lat: 20.0025, lng: 73.7880, info: 'Free medical camp at Ramkund — 24/7' },
    { name: 'Trimbak Medical Camp', lat: 19.9335, lng: 73.5298, info: 'Medical camp near Trimbakeshwar Temple' },
    { name: 'Wockhardt Hospital', lat: 19.9876, lng: 73.7732, info: 'Private hospital with emergency care' },
  ],
  police: [
    { name: 'Ramkund Police Post', lat: 20.0030, lng: 73.7893, info: 'Kumbh security police post at Ramkund' },
    { name: 'Panchavati Police Station', lat: 20.0010, lng: 73.7856, info: 'Main police station — 0253-2510888' },
    { name: 'Trimbakeshwar Police', lat: 19.9328, lng: 73.5290, info: 'Police station at Trimbakeshwar' },
  ],
  parking: [
    { name: 'Parking Zone A (Nashik)', lat: 20.0102, lng: 73.7836, info: 'Capacity: 5,000 vehicles. Shuttle available.' },
    { name: 'Parking Zone B', lat: 19.9968, lng: 73.7948, info: 'Capacity: 3,000 vehicles. 2km from Ramkund.' },
    { name: 'Trimbak Parking', lat: 19.9345, lng: 73.5315, info: 'Parking for Trimbakeshwar visitors.' },
  ],
  transport: [
    { name: 'Nashik Bus Stand (CBS)', lat: 20.0008, lng: 73.7804, info: 'Main MSRTC bus stand — Free Kumbh shuttle point' },
    { name: 'Nashik Road Railway Station', lat: 19.9929, lng: 73.8209, info: 'Main railway station, 8km from Ramkund' },
    { name: 'Nashik City Railway Station', lat: 20.0002, lng: 73.7936, info: 'City railway station closer to Ramkund' },
  ],
  toilets: [
    { name: 'Toilet Complex 1 (Ramkund)', lat: 20.0033, lng: 73.7900, info: 'Mobile toilet complex — 50 units' },
    { name: 'Toilet Complex 2 (Panchavati)', lat: 20.0055, lng: 73.7914, info: 'Permanent toilet facility' },
    { name: 'Toilet Complex 3 (Trimbakeshwar)', lat: 19.9330, lng: 73.5285, info: 'Toilet facility near Kushavart Kund' },
  ],
};

/* ===== BREAKING NEWS TICKER ===== */
const TICKER_ITEMS = {
  en: [
    '🔔 First Shahi Snan on August 29, 2027 at Ramkund Ghat, Nashik',
    '🕉️ Free shuttle service between Nashik and Trimbakeshwar',
    '📢 Register for free accommodation at government dharamshalas',
    '⚠️ Carry identity proof for entry to restricted zones',
    '🚑 Emergency helpline: 108 | Police: 100 | Control Room: 1800-XXX-XXXX',
    '🙏 Kumbh Mela Nashik 2027 — Jai Jai Gange!',
  ],
  hi: [
    '🔔 प्रथम शाही स्नान 29 अगस्त 2027 को रामकुंड घाट, नाशिक',
    '🕉️ नाशिक-त्र्यंबकेश्वर के बीच मुफ्त शटल सेवा',
    '📢 सरकारी धर्मशाला में मुफ्त ठहरने के लिए पंजीकरण करें',
    '⚠️ प्रतिबंधित क्षेत्रों में प्रवेश के लिए पहचान पत्र साथ रखें',
    '🚑 आपातकालीन हेल्पलाइन: 108 | पुलिस: 100 | नियंत्रण कक्ष: 1800-XXX-XXXX',
    '🙏 कुंभ मेला नाशिक 2027 — जय जय गंगे!',
  ],
  mr: [
    '🔔 पहिले शाही स्नान 29 ऑगस्ट 2027 रोजी रामकुंड घाट, नाशिक',
    '🕉️ नाशिक-त्र्यंबकेश्वर दरम्यान मोफत शटल सेवा',
    '📢 सरकारी धर्मशाळेत मोफत राहण्यासाठी नोंदणी करा',
    '⚠️ प्रतिबंधित क्षेत्रात प्रवेशासाठी ओळखपत्र सोबत ठेवा',
    '🚑 आणीबाणी हेल्पलाइन: 108 | पोलिस: 100 | नियंत्रण कक्ष: 1800-XXX-XXXX',
    '🙏 कुंभ मेळा नाशिक 2027 — जय जय गंगे!',
  ],
};

/* ===== ABOUT KUMBH CONTENT ===== */
const ABOUT_CONTENT = {
  what_is_kumbh_en: `Kumbh Mela is the world's largest religious gathering, attended by hundreds of millions of pilgrims from across the globe. It is held at four sacred locations in India — Prayagraj, Haridwar, Nashik, and Ujjain — based on a rotation linked to the positions of Jupiter, the Sun, and the Moon in the zodiac.

The name "Kumbh" refers to the holy pitcher (kumbh/kalash) of nectar (amrit) that emerged during the churning of the cosmic ocean (Samudra Manthan). Drops of this nectar are believed to have fallen at these four locations, making them eternally sacred.

The origins of Kumbh Mela trace back thousands of years to the Vedic and Puranic traditions. It is mentioned in the Rig Veda and various Puranas. The current systematic form of Kumbh Mela is believed to have been organized by Adi Shankaracharya in the 8th century CE.`,

  nashik_special_en: `Nashik, situated on the banks of the sacred Godavari river in Maharashtra, is one of the four Kumbh Mela sites. The Nashik Kumbh is also known as "Simhastha" and occurs when Jupiter is in Leo (Simha) and the Sun is in Aries (Mesh).

Trimbakeshwar, located 28km from Nashik, is the source of the Godavari river and home to one of the 12 sacred Jyotirlingas (divine light manifestations of Lord Shiva). The Shahi Snan at Nashik's Ramkund and Trimbakeshwar's Kushavart Kund are considered among the most purifying acts in Hindu religious tradition.

Nashik is also deeply connected to the Ramayana — it is the place where Lord Rama, Sita, and Lakshmana spent significant years of their 14-year exile at Panchavati. The sacred banyan trees at Panchavati still stand.`,

  shahi_significance_en: `The "Shahi Snan" (Royal Bath) is the most sacred and spectacular event of the Kumbh Mela. The word "Shahi" means royal, and these bathing processions involve elaborate, grand processions of akharas (monastic orders) with their saints, elephants, horses, and decorated chariots.

The timing of each Shahi Snan is determined by precise astronomical calculations based on the positions of the sun, moon, and Jupiter. Bathing at these specific times is believed to purify the soul of all sins accumulated over multiple lifetimes and to grant moksha (liberation from the cycle of rebirth).

The sequence of akharas in the Shahi Snan procession follows a strict historical order determined centuries ago. Witnessing or participating in the Shahi Snan is considered among the highest religious privileges in Hindu tradition.`,
};

/* ===== GALLERY IMAGES ===== */
const GALLERY_IMAGES = [
  { src: 'https://picsum.photos/seed/kumbh1/200/200', alt: 'Ghat at Nashik' },
  { src: 'https://picsum.photos/seed/kumbh2/200/200', alt: 'Ramkund Puja' },
  { src: 'https://picsum.photos/seed/kumbh3/200/200', alt: 'Trimbakeshwar Temple' },
  { src: 'https://picsum.photos/seed/kumbh4/200/200', alt: 'Akhara Procession' },
  { src: 'https://picsum.photos/seed/kumbh5/200/200', alt: 'Godavari River' },
  { src: 'https://picsum.photos/seed/kumbh6/200/200', alt: 'Devotees at Ghat' },
  { src: 'https://picsum.photos/seed/kumbh7/200/200', alt: 'Lamps at Ghat' },
  { src: 'https://picsum.photos/seed/kumbh8/200/200', alt: 'Sadhus at Kumbh' },
  { src: 'https://picsum.photos/seed/kumbh9/200/200', alt: 'Nashik Market' },
];
